### ISSUE TITLE
Document that _User and _Installation are not supported by custom webhooks

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Docs#110]
The UI does not allow the creation of custom webhooks for these classes. This should be covered in the documentation for Webhooks: https://github.com/ParsePlatform/Docs/blob/master/en/common/cloud-code-advanced.mdown

Copying @stanleyw who was discussing this earlier with Min-Young.

**Comment by jeanmartin** [comment]
+1 Is just not allowed in the UI or does Parse not want me to create these triggers for the Parse.User?

**Comment by hramos** [comment]
You can create them in Cloud Code. This issue is specific to Custom Webhooks.


Sent from my iPhone

On Jun 29, 2015, at 6:12 PM, Jan Schwenzien <notifications@github.com<mailto:notifications@github.com>> wrote:


+1 Is just not allowed in the UI or does Parse not want me to create these triggers for the Parse.User?

**Comment by jeanmartin** [comment]
I get that. My question is: bug or feature?
For now I will manually send my "webhook" request from cloud code...

**Comment by hramos** [comment]
This is by design, special subclasses have not been whitelisted for custom Webhooks. Hence this issue was opened to make a note of this in the Docs.

Sent from my iPhone

On Jun 30, 2015, at 2:19 AM, Jan Schwenzien <notifications@github.com<mailto:notifications@github.com>> wrote:


I get that. My question is: bug or feature?
For now I will manually send my "webhook" request from cloud code...

**Comment by brunolazzaro** [comment]
What is the current status of this issue? Right now I'm triggering a custom function webhook and sending the User data as payload, but i think it would be better to enable this. Is there a reason for those classes not being whitelisted from Webhooks?

**Comment by gfosco** [comment]
Committed a note about this in the custom webhooks intro.  We'll have to remove it later when we add support for these classes.
