### ISSUE TITLE
Swift quickstart guides have outdaded parse APIs

### ISSUE THREAD

**Issue by gregpassmore** [ParsePlatform/Docs#117]
The quickstarts for both Analytics and Push don't work, they reference old Parse API that doesnt include blocks, eg PFAnalytics.trackAppOpenedWithRemoteNotificationPayload(userInfo)

and PFAnalytics.trackAppOpenedWithLaunchOptions(launchOptions)

and PFAnalytics.trackEvent("read", dimensions: dimensions)

These all apparently require the usage of blocks now. I just downloaded and got started and had to debug all the quick starts.

**Comment by nlutsenko** [comment]
These actually exist in the APIs and should work...
The piece where it might be not working - is that it won't let you use them in Swift, unless you `import Bolts`. If you add `import Bolts` to the .swift file you are using these from - do they work?

Thanks for reporting these, we'll take a look at how we can improve the experience around these.

**Comment by gregpassmore** [comment]
That worked! The quickstart guides didn't include the import Bolts, but used that code. Here is a screenshot

![screen shot 2015-06-30 at 6 14 02 pm](https://cloud.githubusercontent.com/assets/2468045/8445577/d87e54aa-1f53-11e5-987e-964bb9e80cb3.png)

**Comment by nlutsenko** [comment]
This is no longer needed since Parse SDK [1.8.2](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.8.2).
Closing this one out.
