### ISSUE TITLE
Problem in this documentation https://parse.com/apps/quickstart#parse_push/android/native/existing

### ISSUE THREAD

**Issue by nikhil-raj** [ParsePlatform/Docs#118]
I am following this documentation https://parse.com/apps/quickstart#parse_push/android/native/existing
but not getting the results i.e the push notification. Can some one fix this? It anything missing in this documentation? Please Clarify Everything step by step.

**Comment by hramos** [comment]
It looks like you're asking for technical support. Please visit https://parse.com/help. These issues are specifically for tracking documentation-level issues.
