### ISSUE TITLE
editing/creating custom fields - swift

### ISSUE THREAD

**Issue by driver733** [ParsePlatform/Docs#147]
I would like to edit a custom field in my parse app using parse iOS sdk, however, the suggested way does not seem to work. 

 var user = PFUser()
// other fields can be set just like with PFObject
user["phone"] = "415-392-0202" //ERROR: cannot assign a value of type string to a value of type any object?

**Comment by gfosco** [comment]
I don't see any errors with this... maybe you've got something else wrong?  Please re-open and provide more details if possible, but keep in mind this isn't a support channel.  Thanks.
