### ISSUE TITLE
Typo in iOS Guide Push Notifications section

### ISSUE THREAD

**Issue by cncool** [ParsePlatform/Docs#149]
"pushType: This field is reserved for directing Parse to the push delivery network to be used. If the devic is registered to receive pushes via GCM, this field will be marked "gcm". If this device is not using GCM, and is using Parse's push notification service, it will be blank (readonly)."

device*

**Comment by hramos** [comment]
Can you submit a pull request?

**Comment by gfosco** [comment]
Fixed.
