### ISSUE TITLE
订阅channels时程序会死掉

### ISSUE THREAD

**Issue by liangpengfei** [ParsePlatform/Docs#160]
在按照文中给的方法（        PushService.subscribe(this, "Giants", YourActivity.class);
）来订阅channels时，程序会报如下错误：PushService.subscribe, PushService.unsubscribe, and PushService.setDefaultPushCallback methods cannot be used in conjunction with ParsePushBroadcastReceiver. See ParsePush.subscribe and ParsePush.unsubscribe.查看API可以看出subscribe是废弃方法，可以使用：ParsePush.subscribeInBackground("Giants");来解决这个问题，困扰了我很久，今天终于找到原因了，希望能更正文档，谢谢！

**Comment by hramos** [comment]
Hi @liangpengfei, can you elaborate?

**Comment by liangpengfei** [comment]
@hramos 
Just follow the document's step to SUBSCRIBING TO CHANNELS（订阅通道）,if you use "PushService.subscribe",your app will crash with message "```PushService.subscribe, PushService.unsubscribe, and PushService.setDefaultPushCallback methods cannot be used in conjunction with ParsePushBroadcastReceiver. See ParsePush.subscribe and ParsePush.unsubscribe```" but if you use “ ParsePush.subscribeInBackground” ,your app will work fine.Just show the difference between Chinese document and English document ,in the Chinese document ,the document use the deserted method PushService.subscribe .
Just like those images:
this is the English doc:
![image](https://cloud.githubusercontent.com/assets/7495648/9214741/0462938c-40d4-11e5-8ad3-d1308679c72d.png)
this is the chinese doc:
![image](http://puu.sh/jyhmk/56d7753a1c.png)

**Comment by hramos** [comment]
I understand. We'll leave this open as a Help Wanted issue, and would appreciate a pull request.

**Comment by liangpengfei** [comment]
ok ,Thanks. And may be I can have a try.  But the document still has a lot thing need to be improved so that it could really guide us to use parse without confused.
