### ISSUE TITLE
Update Installation appVersion documentation

### ISSUE THREAD

**Issue by grantland** [ParsePlatform/Docs#174]
`appVersion` isn't guaranteed to always be up-to-date since we try to prevent your app from DDOSing yourself when releasing app updates, since app updates and new app runs occur around the same time for all users and it would cause a spike that may lead you to run over your req/s limit.

https://parse.com/docs/android/guide#push-notifications-installations
https://github.com/ParsePlatform/Parse-SDK-Android/issues/24

**Comment by hramos** [comment]
I've opened #180 which should take care of this.

**Comment by hramos** [comment]
Closing now that #180 has landed.
