### ISSUE TITLE
Add missing Swift examples to PFQueryTableViewController Docs

### ISSUE THREAD

**Issue by derekgould** [ParsePlatform/Docs#182]
When reviewing the docs for this section, selecting "Swift' as the language on a code window causes all code examples to disappear completely. Reproduced in Edge, Google Chrome, IE and Firefox (on Windows 10).

**Comment by hramos** [comment]
I was able to reproduce. It looks like a couple of objc blocks are missing the Swift equivalent, therefore nothing is displayed in those cases. This should be fixed by adding the Swift code example. Can you send a PR?

**Comment by derekgould** [comment]
Sorrywhats a PR?

 

 

Regards,

DG

____________________________________________________________________________
______

Never hold discussions with the monkey when the organ grinder is in the
room.
-Winston Churchill

**Comment by hramos** [comment]
A pull request is how you propose updates to our documentation repo. You can read more in our CONTRIBUTING file: https://github.com/ParsePlatform/Docs/blob/master/CONTRIBUTING.md
