### ISSUE TITLE
Add C# Examples to Performance Guide

### ISSUE THREAD

**Issue by yuriburger** [ParsePlatform/Docs#196]
The query examples are missing from the performance guidance for Parse.com and Unity:

GitHub: Docs / en / common / performance.mdown
Page: https://parse.com/docs/unity/guide#performance

"Not Equal To
For example, let's say you're tracking high scores for a game in a GameScore class. Now say you want to retrieve the scores for all players except a certain one. You could create this query:

<this query example is missing for Unity code>

This query can't take advantage of indexes. The database has to look at all the objects in the GameScore class to satisfy the constraint and retrieve the results. As the number of entries in the class grows, the query takes longer to run."

![1](https://cloud.githubusercontent.com/assets/8437538/9717110/27b56bec-5570-11e5-93a2-8749b1f0bacf.png)

Regards, 

Yuri

**Comment by amo-ej1** [comment]
If you are reading the Android version of the guide you will also bump into the same issue, the Android samples are also not present.

**Comment by hramos** [comment]
This happens when we don't have sample code for a language supported by the platform. This could be fixed by providing examples in C#. Happy to review any pull request that expands these examples.

**Comment by hramos** [comment]
I took care of this in #305
