### ISSUE TITLE
iOS One-To-Many Relationships tutorial doesn't exist

### ISSUE THREAD

**Issue by SirArkimedes** [ParsePlatform/Docs#200]
![screenshot 2015-09-09 16 31 25](https://cloud.githubusercontent.com/assets/3119506/9774864/ea8eaa42-5710-11e5-9150-bbf9795cc3e2.png)

https://parse.com/docs/ios/guide#objects-relational-data
The above link brings you here:
![screenshot 2015-09-09 16 36 59](https://cloud.githubusercontent.com/assets/3119506/9774874/03cf4534-5711-11e5-910d-7468e5a925a1.png)

**Comment by hramos** [comment]
Thanks for the report. That tutorial has been retired. The link will be removed in the next deploy.
