### ISSUE TITLE
parseExpressCookieSession documentation gone

### ISSUE THREAD

**Issue by raae** [ParsePlatform/Docs#202]
This page does not longer exists: https://parse.com/docs/js/api/classes/parseExpressCookieSession.html.

It is referenced here: https://parse.com/docs/js/guide#hosting-user-session-management (and numerous other places).

**Comment by camdagr8** [comment]
https://parse.com/docs/js/guide#hosting-user-session-management  doesn't appear to be working either. It just takes you to the Hosting Getting Started page.

**Comment by pavanka** [comment]
https://parse.com/docs/cloudcode/guide#hosting-user-session-management

**Comment by hramos** [comment]
This seems similar enough to #209 which has a longer thread, so I will close this one.
