### ISSUE TITLE
Express docs are gone

### ISSUE THREAD

**Issue by skhavari** [ParsePlatform/Docs#203]
linked to from https://parse.com/docs/js/guide#cloud-code-modules is this https://parse.com/docs/js/api/classes/express.html which no longer exists.

At min, need to know which version of express is hosted to find the corresponding docs.

**Comment by html5cat** [comment]
@skhavari sorry about that. Looks like recent JS SDK release broke that part of api reference.
 The Parse Express API is a subset of the Express 3.1.0 API. (ref. [google cached page](http://webcache.googleusercontent.com/search?q=cache:K7ACaHxLFEMJ:https://parse.com/docs/js/api/symbols/express.html+&cd=1&hl=en&ct=clnk))

**Comment by shunwen** [comment]
@html5cat the HTTP interface docs are gone too

**Comment by hramos** [comment]
Can you open this issue in @ParsePlatform/team-parse-sdk-js ? These API ref headers are auto-generated by the JS SDK.
