### ISSUE TITLE
404 error with blank javascript/HTML5 project

### ISSUE THREAD

**Issue by zenev** [ParsePlatform/Docs#207]
The page https://www.parse.com/downloads/javascript/parse-js-blank/latest gives a 404 error. This is linked to from this page https://www.parse.com/apps/quickstart?app_id=idebate#social/web/new and this one: https://www.parse.com/docs/downloads.

**Comment by hramos** [comment]
This issue is not covered by this repository, but is part of the parse.com website itself. Thanks for the heads up.

**Comment by hramos** [comment]
Fixed.
