### ISSUE TITLE
Swift sample code missing for various sections

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Docs#21]
Some of the files in the iOS guide are missing Swift examples (search for "no swift example"):

Docs/en/ios/handling-errors.mdown
Docs/en/ios/in-app-purchases.mdown
Docs/en/ios/local-datastore.mdown
Docs/en/ios/push-notifications.mdown
Docs/en/ios/queries.mdown
Docs/en/ios/user-interface.mdown

**Comment by Lucashuang0802** [comment]
Finished editing from the item one to item four in pull request #41, please review and approve if that's what you guys need. And I will finish the rest.

**Comment by hramos** [comment]
Linking #45 and #47 here.

**Comment by Lucashuang0802** [comment]
Link #58

**Comment by Lucashuang0802** [comment]
#73 This issue can be close

**Comment by nlutsenko** [comment]
It looks like there are couple more missing:
https://github.com/ParsePlatform/Docs/blob/a9ab036799839dd94badad00341f7f5ccba041f2/en/ios/push-notifications.mdown#L685
https://github.com/ParsePlatform/Docs/blob/2aa74b0d90d48edc662193085a8fda8c7bae5df2/en/common/relations.mdown#L201
https://github.com/ParsePlatform/Docs/blob/2aa74b0d90d48edc662193085a8fda8c7bae5df2/en/common/relations.mdown#L249

**Comment by Lucashuang0802** [comment]
I will look into it when I have time tonight and hopefully I can make PR tomorrow. Thanks.

**Comment by hramos** [comment]
Thanks for all your help, it's really appreciated.

**Comment by Lucashuang0802** [comment]
#78 is merged. Please check whether there are still missing pieces of **Swift** codes for **iOS**

**Comment by hramos** [comment]
Awesome work! This is really appreciated.

I think the only missing pieces are in `en/common/relations.mdown`, which I missed in my initial pass when this issue was opened.

**Comment by Lucashuang0802** [comment]
Okay, I will take a look at that.

**Comment by Lucashuang0802** [comment]
I just made a double check and I can't find any `// no swift example` in the `en/common/relations.mdown`. Can you double check? Thanks.

**Comment by hramos** [comment]
Looks like we now have full Swift coverage in the Docs. Thank you very much!

**Comment by Lucashuang0802** [comment]
Sounds good. @ me if you any of them. lol. Thanks.
