### ISSUE TITLE
Quickstart iOS Guide

### ISSUE THREAD

**Issue by lfarah** [ParsePlatform/Docs#217]
[The iOS Quckstart Page](https://www.parse.com/apps/quickstart#parse_data/mobile/ios/swift/new) isn't updated for Swift 2, and I'd love to update it, but I didn't find it on the Github. 
The only thing I found was [Docs/en/ios/getting-started.mdown](https://github.com/ParsePlatform/Docs/blob/master/en/ios/getting-started.mdown), but there's no example code and the links are broken.

**Comment by hramos** [comment]
The QuickStart is not powered by this specific project, and is instead part of the parse.com website itself. If you want to provide an updated set of code, I should be able to open a PR against the website.

**Comment by hramos** [comment]
Please reopen if this is still an issue.
