### ISSUE TITLE
Cloud Code JavaScript SDK API Reference Missing

### ISSUE THREAD

**Issue by eyeofhell** [ParsePlatform/Docs#221]
```https://github.com/ParsePlatform/Docs/blob/master/en/common/hosting.mdown``` file, link named "Express API docs" leads nowhere.

**Comment by martianmartian** [comment]
they offer O support don't they?

**Comment by eyeofhell** [comment]
Sorry, English is not my native, I can't understand this :(. What do you mean by "O support" and who are "they"?

**Comment by martianmartian** [comment]
O means zero, means they offer no support at all

**Comment by hramos** [comment]
The JavaScript API Reference is generated from the source of the JavaScript SDK. The Cloud Code APIs are not part of the SDK that was open sourced, therefore the docs are no longer present as of version 1.6.0. The methods are still accessible to applications hosted on Cloud Code and therefore there is some value to restoring these API references. I will look into the restoration of these docs.

**Comment by hramos** [comment]
See [Express 3.x API Reference](http://expressjs.com/en/3x/api.html). The broken links will be taken care of when #289 is merged.

**Comment by hramos** [comment]
Fixed.
