### ISSUE TITLE
Parse.jar not found in the Parse-1.10.3.zip

### ISSUE THREAD

**Issue by Tushaarv** [ParsePlatform/Docs#227]
I downloaded the Android SDK as mentioned in the documentation. When I unzip it, the parse.jar file is not found. It was present for earlier versions I used. However when I tried for 1.10.3 the parse.jar file was missing.

**Comment by grantland** [comment]
This seems like an issue with the download we're providing and we're working to resolve this.

Could you also point me to the docs that reference parse.jar? The recommended usage should be using Maven Central as per our instructions at https://github.com/ParsePlatform/Parse-SDK-Android

**Comment by Tushaarv** [comment]
https://parse.com/apps/quickstart#parse_data/mobile/android/native/existing

**Comment by grantland** [comment]
Thanks, the downloads artifact should be working now and our quickstarts should be updated soon!

**Comment by Tushaarv** [comment]
Thanks downloads working fine
