### ISSUE TITLE
Cloude code is out from docs from js documentation

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/Docs#228]
http://parse.com/docs/js/guide

Cloud code docs is missing from the main JS docs page. Please look into it. 

Wish I had saved the HTML page when it was available!

**Comment by pavanka** [comment]
we moved it to its own top-level

https://parse.com/docs/cloudcode/guide

**Comment by pavanka** [comment]
cloud code is not specific to any platform instead it is its own platform
https://github.com/ParsePlatform/Docs/tree/master/en/cloudcode

**Comment by srameshr** [comment]
May be you should mention it at the beginning of the JS docs page.
