### ISSUE TITLE
Express Documentation

### ISSUE THREAD

**Issue by camdagr8** [ParsePlatform/Docs#229]
None of the Express Middleware links work and the API Ref. here: https://parse.com/docs/js/api/ doesn't have any of the info anymore either. Does anyone know where to find any docs on this stuff?

**Comment by hramos** [comment]
Yeah, it looks like we're missing quite a few reference headers. These headers are actually autogenerated from code in the JavaScript SDK itself, can you open this issue in the @ParsePlatform/team-parse-sdk-js repository?
