### ISSUE TITLE
Swift typo in PFLogInViewController Documentation

### ISSUE THREAD

**Issue by Audentia** [ParsePlatform/Docs#238]
so for the Swift code snippets it says:
```
func logInViewController(controller: PFLogInViewController, didLogInUser user: PFUser!) -> Void {
  self.dismissViewController(true, completion: nil)
}

func logInViewControllerDidCancelLogIn(controller: PFLogInViewController) -> Void {
  self.dismisViewControllerAnimated(true, completion: nil)
}
```

first function is missing "Animated" second one is missing second "s" of dismiss

**Comment by nlutsenko** [comment]
Nice catch. Will gladly review a Pull Request for this.

**Comment by Audentia** [comment]
OK! will do (sorry full disclosure this is my first contribution, so I’m figuring forking / pull requests out, but it should be up in a few)

Douglas Hewitt
doughewitt4@gmail.com
(510) 495-5329

**Comment by Audentia** [comment]
submitted pull request #239

**Comment by nlutsenko** [comment]
All merged. Closing this one out.
