### ISSUE TITLE
Javascript Guide out of date?

### ISSUE THREAD

**Issue by solange** [ParsePlatform/Docs#247]
Hello, I'm completely confused trying to get started with the JS SDK: https://parse.com/docs/js/guide

For example, is this still valid?: "Our JavaScript SDK is based on the popular Backbone.js framework."  I can't get the Todo tutorial to work with the latest javascript SDK, I think because of the changes to parse-latest.js. 

Are there updated guides or tutorials available? 
Cheers

**Comment by gfosco** [comment]
The Todo example is ancient and I would suggest going through the quickstart https://parse.com/apps/quickstart and looking at the docs  https://parse.com/docs/js/guide as we have no modern JS tutorials listed.  

Andrew just updated the docs to remove the reference to backbone.  Thanks.

**Comment by solange** [comment]
Thanks gfosco, looking forward to new tutorials. Cheers

**Comment by Mamonaku** [comment]
Hi Fosco,
any chance Parse.com will provide a basic example as to how to use the new JS SDK? How can I replace Views/Collections with Backbone?
