### ISSUE TITLE
Missing Platform guide on using Cloud Code

### ISSUE THREAD

**Issue by Ralphilius** [ParsePlatform/Docs#264]
In [this section](https://www.parse.com/docs/cloudcode/guide#cloud-code-cloud-functions) of cloud code guide, it is said to go back to Platform SDKs to learn how to call a cloud code. However, there are no guide at least in Android and iOS.

**Comment by hramos** [comment]
Thanks for bringing this up - #279 should address this

**Comment by hramos** [comment]
#279 has been merged.
