### ISSUE TITLE
"id" as reserved keyword

### ISSUE THREAD

**Issue by Natelegreat1** [ParsePlatform/Docs#266]
I think the keyword "id" should not be available for PFObjects.
OR - at the very least - it should not be allowed in the Data Browser.

Though it can be set to any value in code, the data is shown visually as a duplicate of the objectId column.
![screen shot 2015-11-20 at 11 51 54 am](https://cloud.githubusercontent.com/assets/2666640/11309751/9fc6a0f8-8f93-11e5-95f1-cdc4a6554868.png)

**Comment by hramos** [comment]
This does not appear to be an actual issue with the Documentation site. You may want to bring this up in one of the SDK repositories.

**Comment by Natelegreat1** [comment]
It was just a suggestion! Feel free to forward it to the appropriate department… Not sure where you’d want it.
It’s not SDK related…
