### ISSUE TITLE
Android version of the Push Notification troubleshooting guide

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Docs#28]
Most of the content at https://www.parse.com/docs/ios/guide#push-notifications-troubleshooting applies to Android as well, with small code sample updates.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hramos** [comment]
Already shipped.
