### ISSUE TITLE
Error The supplied Facebook session token is expired or invalid.

### ISSUE THREAD

**Issue by robtg4** [ParsePlatform/Docs#281]
Need an updated solution to solve the inability to log into Facebook and store data via Parse on react native app. Solution cited here https://www.parse.com/questions/unable-to-login-with-facebook no longer works given that Facebook has changed its settings around. Thanks!

**Comment by hramos** [comment]
Hi there, we use this repository to track issues in our documentation. For technical assistance, please see https://parse.com/help
