### ISSUE TITLE
Broken link to CLI for OS X

### ISSUE THREAD

**Issue by imagine** [ParsePlatform/Docs#283]
On https://parse.com/docs/downloads

The link to download the OS X CLI is broken

**Comment by nlutsenko** [comment]
Indeed it is. Working on a fix, will close the issue when it's fixed.

**Comment by nlutsenko** [comment]
Fixed on the original page.
We also have a new Open Source Hub [here](https://parseplatform.github.io) which might be more helpful than downloads page.
