### ISSUE TITLE
parseExpressHttpsRedirect documentation returns 404 error

### ISSUE THREAD

**Issue by geordie78** [ParsePlatform/Docs#287]
The following link in https://parse.com/docs/cloudcode/guide#hosting -> Cloud Code Hosting -> Dynamic Websites -> User Session Management returns a 404 error....

"When you work with user data, you should use HTTPS whenever possible. To protect your app and your users, the parseExpressCookieSession middleware requires you to use HTTPS. For your convenience, we also provide a parseExpressHttpsRedirect middleware for redirecting all HTTP requests to HTTPS. Please see its documentation for details."

The word "documentation" in the last line above links to the following missing page:

https://parse.com/docs/js/api/symbols/parseExpressHttpsRedirect.html

**Comment by hramos** [comment]
Thanks for the report. This is due to some changes in how the docs are generated, and is being tracked in #221.

**Comment by hramos** [comment]
Closed prematurely. This will be fixed by #289 once it is merged.
