### ISSUE TITLE
Need much better docs for Heroku + MongoLab deployment

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/docs#324]
The docs on this page are very slim and its not clear at all, I think we need a better howto with exact step by step.. I have tried this with the sample project but a bunch of in the index.js and where you get your keys from etc is missing.. please take the time to write a exact step by step.

https://github.com/ParsePlatform/Docs/blob/master/en/server/deploying.mdown

**Comment by dirkpostma** [comment]
+1

On first reading, some questions popped up, which is indication of a low quality section:

What is "create a repo"?
What is meant by "the Express app"?
Parse Server middleware "mounted"?
...rephrase this entire

**Comment by nlutsenko** [comment]
That sounds about right, this might be quite challenging for anyone who is not coming from a dev background.
I recommend sending a PR, as code wins arguments, or in this case documentation wins arguments.
Also, we have quite an extensive guide on different deployment flows on the wiki for the server [here](https://github.com/parseplatform/parse-server/wiki).

**Comment by gateway** [comment]
@nlutsenko thanks for the link I was looking at that the other day and nice to see more guides coming online.  One thing I think that should be addressed is the way to scale the parse-server across multi servers.  I'm mainly coming from python, bit or ruby, php and C so not sure how to handle node.js autoscaling and what you guys recommend works.

**Comment by hramos** [comment]
Stay tuned. We should have more content available soon. Don't forget to check out https://github.com/ParsePlatform/parse-server/wiki as well.

**Comment by steven-supersolid** [comment]
There are a couple of points regarding database migration that I'm confused about. I don't want to make a pull request as I'm not a DBA :) Hope these can be addressed by someone that knows the system/wrote the migration script.

> Ensure that the user in the connection string has admin privileges, as the migration tool will set some parameters automatically during the process.

Which roles are OK and what parameters are set? I initially took this to be root but dbOwner seems to work fine and that seems to be working in tutorials that use the MongoLab sandbox. It would be helpful to know the parameters so we can check if everything went as planned.

> The failIndexKeyTooLong parameter must be set to false

This is still set true after migrating, should we set this manually and what will happen if we don't? Setting this requires admin database access which is not available on MongoLab sandbox and shared plans.
