### ISSUE TITLE
Parse database migration issue, now can't do anything

### ISSUE THREAD

**Issue by hafizapp** [ParsePlatform/Docs#329]
<img width="1127" alt="screen shot 2016-01-30 at 2 07 33 am" src="https://cloud.githubusercontent.com/assets/1691606/12686989/4d026ad2-c6f7-11e5-8042-a543d491b56d.png">

Today morning I am trying to migrate my database to mongoDB, and it goes to second step. And instead of clicking "Finalize" I clicked on "Stop"

now dashboard of this App doesn't allow me to do re-initiate the migration process. Can any one please help regarding this matter.

@daaku @tmc @kashif @jamesyu @Palleas

**Comment by jamesyu** [comment]
this is a bug and we are fixing it. Please refer to this tracking issue instead: https://github.com/ParsePlatform/parse-server/issues/42
