### ISSUE TITLE
Document removal of Parse.Cloud.useMasterKey and Parse.User.current() in parse-server

### ISSUE THREAD

**Issue by drew-gross** [ParsePlatform/docs#335]
useMasterKey needs to be specified on a per-query basis. The current user should be retrieved from the request object, I think.

cc @gfosco @hramos

**Comment by hramos** [comment]
This is covered in the wiki for now: https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse#cloud-code
