### ISSUE TITLE
cannot find  "head over to the Push QuickStart"

### ISSUE THREAD

**Issue by john1jan** [ParsePlatform/Docs#350]
cannot find document for  **head over to the Push QuickStart** for android

**Comment by hramos** [comment]
Hi @john1jan, can you point me to the specific document that has a broken link?

**Comment by john1jan** [comment]
I went to this link for setting up PushNotification in my android app.

https://parse.com/docs/android/guide#push-notifications-installations

in which they have said

"If you haven't installed the SDK yet, [head over to the Push QuickStart](https://parse.com/apps/quickstart#parse_push) to get our SDK up and running."

when i click on **head over to Push QuickStart**  it goes to [this page](https://parse.com/apps/quickstart#parse_push)

There it asks me for the "Select a product".

1. I selected **Data**
2. Then it asks me to "Select Environment". I selected "Mobile"
3. Then it asks me to "Select Platform". I selected "Android". Phew...... :(
4. Then it asks me to "Select language". I selected "Native(Java)"
5. Then it asks me to "Select Type of Project". I Selected "Existing Project"

And finally it will show [this page](https://parse.com/apps/quickstart#parse_data/mobile/android/native/existing)

But this is not the  **Push QuickStart**.

Why you guys are making the docs so complex to access ?

Why cant there be search for a particular keyword ?

There is [Push notification tutorial](https://parse.com/tutorials/android-push-notifications) which also points to **Push QuickStart for Android** , which eventually leads to same page.

Finally . Where is the **Push QuickStart for Android** ?. It would be better if you could comment the link here ?

**Comment by hramos** [comment]
The push notifications quickstart has been moved to the Parse Server wiki: https://github.com/ParsePlatform/parse-server/wiki/Push#quick-start

I'll open a PR to fix these broken links.

**Comment by hramos** [comment]
Fixed in 7487acc140317958191d9c8268676a5356d0155c.

**Comment by john1jan** [comment]
But i am not using parse server. We are still in old parse version. Can you provide the old pushnotification doc

**Comment by hramos** [comment]
With both Parse Server and Parse.com Push, the client-side configuration steps are pretty much the same. You don't have to configure the server URL when using Parse.com.

For the server-side, if targeting iOS you will want to upload the certificates to the Parse.com dashboard.

We have intentionally removed instructions for setting up a new push notifications app on Parse.com as the hosted service is shutting down. Instead of setting up a new app with Parse.com push, we highly recommend using Parse Server for push or another push notifcations provider.

**Comment by john1jan** [comment]
Ok...Thanks for your support. I am able to configure from parse server docs.
