### ISSUE TITLE
Error 159 bug filing missing link.

### ISSUE THREAD

**Issue by carleek** [ParsePlatform/Docs#351]
In your error codes english document you state:

> If your requests are being rejected with a 159 error code, please file a bug report for further instructions on how to resolve the issue.

With a link to file a bug.  However, the link is dead:
[https://github.com/ParsePlatform/Docs/blob/master/help#report](url)

Oh, and I am getting this error... I would like to know where to file the bug, it's causing a lot of crashes for my users.

**Comment by nlutsenko** [comment]
The link is not dead, but rather it's domain agnostic and we probably should update it to be full URL.
The correct link is https://parse.com/help#report
