### ISSUE TITLE
iOS SDK [Parse enableLocalDatastore] doesn't work

### ISSUE THREAD

**Issue by jgaull** [ParsePlatform/docs#352]
The docs say to use `[Parse enableLocalDatastore]`, but the correct way to do this is inside the initializeWithConfiguration block:

```
[Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"ParseAppId";
        configuration.clientKey = @"ParseClientKey";
        configuration.server = @"ServerUrl";
        configuration.localDatastoreEnabled = YES;
}]];
```

**Comment by nlutsenko** [comment]
It actually depends on whether you are using Parse Server or not.
`enableLocalDatastore` API still works if you are not using ParseClientConfiguration.

PRs are very welcome and I would gladly review any updates.

**Comment by jgaull** [comment]
Great, thanks! I'll try and get a PR together this week.

On Wednesday, April 13, 2016, Nikita Lutsenko <notifications@github.com>
wrote:

> It actually depends on whether you are using Parse Server or not.
> enableLocalDatastore API still works if you are not using
> ParseClientConfiguration.
>
> PRs are very welcome and I would gladly review any updates.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/Docs/issues/352#issuecomment-209578734>
>


-- 
This message was typed on a tiny, error prone keyboard.
