### ISSUE TITLE
No examples for REST API Relations

### ISSUE THREAD

**Issue by workslon** [ParsePlatform/docs#354]
Hello,

is it possible to return the examples for REST API Relations section? They were just there (https://parse.com/docs/rest/guide#relations), but now there is only "# No REST API example" displayed.

Thank you in advance for looking into this!

Cheers,
Vitaliy

**Comment by hramos** [comment]
The Relation Guide has never had REST API examples actually, as the initial version was iOS only.

If you can submit a PR which adds these examples I'd be happy to take a look.
