### ISSUE TITLE
Docs links are broken 

### ISSUE THREAD

**Issue by ranhsd** [ParsePlatform/Docs#359]
Hi, 
It seems like your links for your docs are broken.. 
if you go to: [http://parse.com/docs](url) and select one of links (android,ios, javascript etc.) you get 404 (page not found) 

I think you need to change the path to point to: https://parse.com/docs/android/guide (this is an example of link to the android guide but you need to do it for all of them)

**Comment by hramos** [comment]
This is being fixed today. A static document page was deployed, which lacked the actual links to the guides. You can visit https://parseplatform.github.io to get the right set of links.
