### ISSUE TITLE
android guide half broken

### ISSUE THREAD

**Issue by Toofoo** [ParsePlatform/Docs#360]
many issues on the parse android sdk guide, some links seem broken, the text is mixed with other sdk guide (for i.e in the Queries part or in Relations parts ....

**Comment by hramos** [comment]
Can you provide more specifics?

**Comment by Toofoo** [comment]
Simply click on th link : http://parseplatform.github.io/docs/android/guide/#queries
you wil see that only the first paragraph (Basic Query) is correctly displayed, then you jump directly to the User paragraph. I gess some HTML tag are missing

**Comment by hramos** [comment]
Should be resolved now.

**Comment by Toofoo** [comment]
I'm sorry but there is the same issue for the "Relation" paragraph. And I didn't check all the other paragraphs but there might be some other issue like this.

ex: http://parseplatform.github.io/docs/android/guide/#relations

**Comment by hramos** [comment]
Should be good now

**Comment by Toofoo** [comment]
there still some bad display bellow here : http://parseplatform.github.io/docs/android/guide/#using-arrays

**Comment by hramos** [comment]
Resolved.
