### ISSUE TITLE
where are the resources limit of cloud code disappeared?

### ISSUE THREAD

**Issue by kalitas** [ParsePlatform/Docs#361]
is this still valid:
Cloud functions will be killed after 15 seconds of wall clock time. beforeSave functions and afterSave functions will be killed after 3 seconds of run time. If a Cloud function or a beforeSave/afterSave function is called from another Cloud Code call, it will be further limited by the time left in the calling function. For example, if a beforeSave function is triggered by a cloud function after it has run for 13 seconds, the beforeSave function will only have 2 seconds to run, rather than the normal 3 seconds.

**Comment by hramos** [comment]
Those limits are still true in hosted Parse.com Cloud Code.

**Comment by kalitas** [comment]
and in aws is there limit? i wanna do some logics in the cloud code in the before save or after save. are there still 3 sec?

**Comment by flovilmart** [comment]
there are no limits in cloud code in parse-server like Hector said.

**Comment by kalitas** [comment]
thanks
