### ISSUE TITLE
Are these hosted anywhere?

### ISSUE THREAD

**Issue by brandly** [ParsePlatform/Docs#362]
all the old links, like https://www.parse.com/docs/js/, are redirecting me to https://parseplatform.github.io/ now

**Comment by OmgImAlexis** [comment]
Goto https://parseplatform.github.io/#sdks and click guide on the SDK you're using, for example the JS guide is now hosted at https://parseplatform.github.io/docs/js/guide/

**Comment by brandly** [comment]
thanks!! looks great
