### ISSUE TITLE
Relations section is missing from REST API guide

### ISSUE THREAD

**Issue by zaach** [ParsePlatform/Docs#369]
It would help the dozens of us REST API users immensely if there were Relations examples.

**Comment by hramos** [comment]
You can find examples using the REST API under [Relational Queries](http://parseplatform.github.io/docs/rest/guide/#relational-queries) as well as [Updating Relations](http://parseplatform.github.io/docs/rest/guide/#relations).

**Comment by zaach** [comment]
Not helpful for figuring out how to work with arrays of pointers but I managed to get it working.
