### ISSUE TITLE
Windows Phone Push Notification documentation has been removed

### ISSUE THREAD

**Issue by d370urn3ur** [ParsePlatform/Docs#373]
On the .NET SDK there is a broken link to "head over to the Push QuickStart" (https://github.com/ParsePlatform/parse-server/wiki/Push#quick-start).  I found the updated docs here: https://github.com/ParsePlatform/parse-server/wiki/Push#quick-start but there is zero info on setting up Windows Phone Push Notifications.

**Comment by flovilmart** [comment]
Not sure this is relevant, parse-server don't support Windows Phone Push anymore.
