### ISSUE TITLE
swift examples do not work with swift 3

### ISSUE THREAD

**Issue by nitrag** [ParsePlatform/Docs#378]
I had the examples working then I upgraded to swift 3, now they are not working. I can't seem to figure out the right syntax. I'm a complete swift newb.

Docs:

```
user.signUpInBackgroundWithBlock {
    (succeeded: Bool, error: NSError?) -> Void in
    if let error = error {
      let errorString = error.userInfo["error"] as? NSString
      // Show the errorString somewhere and let the user try again.
    } else {
      // Hooray! Let them use the app now.
    }
  }
```

Closest I've got is:

```
user.signUpInBackground {
       (succeeded: Bool, error: Error?) -> Void in
       if let error = error 
            let errorString = error.userInfo["error"] as? NSString
            // Show the errorString somewhere and let the user try again.
       } else {
           // Hooray! Let them use the app now.
       }
}
```

Except I still get this error:
ERROR: `Value of Type 'Error' has no member 'userInfo'

BUT

Now I'm reading in the API docs that `signUpInBackground` is deprecated and we should just be using `signUp()` ??? So all the code examples are deprecated?? So are all the examples in the docs needing to be updated since they use the deprecated API methods?

[Deprecated?](https://parseplatform.github.io/Parse-SDK-iOS-OSX/api/Categories/PFUser%28Deprecated%29.html)
[New?](https://parseplatform.github.io/Parse-SDK-iOS-OSX/api/Categories/PFUser%28Synchronous%29.html#/c:objc%28cs%29PFUser%28im%29signUp) 

If I use the new API methods (asynchronous) how do we perform the functions of what would be in the callback/block? 

I'm a iOS/Swift Newbie but I'm rocking and rolling with PHP/JS/Parse-Server so it bugs me that I'm completely stumped on this.

@nlutsenko

**Comment by nitrag** [comment]
Here's the proper way to have a user signup:

```
user.signUpInBackground {
    (success, error) -> Void in
    if let error = error {
        if let errorString = (error as NSError).userInfo["error"] as? String {
            NSLog(errorString);
        }
    } else {
        // Hooray! Let them use the app now.
        NSLog("Signed up!");

    }
}
```

and login:

```
PFUser.logInWithUsername(inBackground: self.email.text!, password:self.password.text!) {
    (user: PFUser?, error: Error?) -> Void in
    if let error = error {
        if let errorString = (error as NSError).userInfo["error"] as? String {
            NSLog(errorString);
        }
    } else {
        // Hooray! Let them use the app now.
        NSLog("Logged in!");
    }
}
```

Maybe someone else can explain the use of `Error` instead of `NSError` because getting the `errorString` to work was also a doozie.

**Comment by AmbroiseCollon** [comment]
Swift 3 has changed the way objective-c methods are translated into swift. In short, the methods name are now more concise.

Also, `Error` type has now replaced the old `NSError`. So what you can do is :  

```
if let error = error {
    print(error.localizedDescription)
} else {
    // Hooray! Let them use the app now.
    print("Logged in!");
}
```

More info [here](https://swift.org/blog/swift-3-0-released/)

**Comment by hramos** [comment]
Feel free to send a PR with any fixes. I don't think there has been a sweep over the Swift code examples since Swift 3.

**Comment by virajpadte** [comment]
Using error.localizedDescription works perfectly!

**Comment by flovilmart** [comment]
@AmbroiseCollon, @nitrag as @hramos mentioned, feel free to open a PR with updated Swift3 compatible code! Thanks!
