### ISSUE TITLE
Rest Guide: sidebar incorrectly links to Quick Reference sub-sections

### ISSUE THREAD

**Issue by zaach** [ParsePlatform/Docs#380]
The Quick Reference headings collide with the section headings.

**Comment by hramos** [comment]
Can you include more details? If it's a small enough fix, I can take a look at a PR if you want to open one.

**Comment by zaach** [comment]
Sure, STR:
- Go to http://parseplatform.github.io/docs/rest/guide
- Click on e.g. 'Objects' in sidebar
- Observe content scrolled to Quick Reference - Objects section

Expected: content should scroll to the full Objects section

I'm not sure how docs are built/linked together.

**Comment by TonyTangAndroid** [comment]
I am also experiencing a similar issue. Let's use API as signup as an example. 
The following link should locate to user signup section. But it did not. 
[https://parseplatform.github.io/docs/rest/guide/#users-signingup](https://parseplatform.github.io/docs/rest/guide/#users-signingup)

**Comment by TonyTangAndroid** [comment]
It turns out that the following link is the correct one that is referencing  the signing up document. 
[https://parseplatform.github.io/docs/rest/guide/#signing-up](https://parseplatform.github.io/docs/rest/guide/#signing-up)

The difference is **#users-signingup** vs **#signing-up**

**Comment by TonyTangAndroid** [comment]
Try to search **/1/users/<objectId>**, you will find the wrong referenced link.

**Comment by flovilmart** [comment]
All the links should be valid now, If you encounter more broken links, pleas open a new issue!

**Comment by TonyTangAndroid** [comment]
Oh no, even the whole website is returning 404 : https://parseplatform.github.io/
@flovilmart

**Comment by flovilmart** [comment]
This is ok, the repositories have been transferred. Now they are on http://parseplatform.org

**Comment by TonyTangAndroid** [comment]
I see. Thanks for the update.
