### ISSUE TITLE
Duplicate #security links in the iOS Guide

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [ParsePlatform/Docs#383]
There are two internal links with href="#security". So when you click on the Security in the column underneath Handling Errors it takes you to Security located in Sessions > Security.

**Comment by hramos** [comment]
Can you send a PR?

**Comment by jordanhbuiltbyhq** [comment]
Unfortunately I haven't the time to do a proper fix. I think the best solution is to not just fix this one case but to prefix the main heading before the subheading to prevent this from happening again. It may already be occurring for other subcategories.

**Comment by flovilmart** [comment]
This should be fixed now, feel free to open a new issue if you encounter more broken/dead links
