### ISSUE TITLE
cloud code: beforeFind not documented

### ISSUE THREAD

**Issue by jonas-db** [ParsePlatform/Docs#384]
The documentation does not tell anything about the beforeFind trigger available since 2.2.20 

http://parseplatform.github.io/docs/cloudcode/guide/

**Comment by hramos** [comment]
Nice find. Happy to review a PR if someone wants to add this.

**Comment by henninghorn** [comment]
@hramos: It seems like there's a PR waiting to get merged regarding this issue: https://github.com/ParsePlatform/docs/pull/376

**Comment by hramos** [comment]
Merged.
