### ISSUE TITLE
📙 Documentation on iOS Session ACL is wrong

### ISSUE THREAD

**Issue by richardgroves** [ParsePlatform/Docs#385]
The iOS [security section](http://docs.parseplatform.org/ios/guide/#security) says that ACL for a Session object is read/write the owning user only, but [#1633](https://github.com/ParsePlatform/parse-server/issues/1633) indicates that the ACL is Public Read+Write and that is correct as security is handled via non-ACL methods for Session objects.

**Comment by flovilmart** [comment]
@richardgroves are you willing ot open a PR?

**Comment by TomWFox** [comment]
I couldn't find the bit you're referring to, could you provide an updated link and quote the section from the docs? - then I will look at making a PR.

**Comment by TomWFox** [comment]
I've had a closer look now and still can't find the section, so I am going to close this for now.

If you would like to direct me to it or open a PR I would be happy to follow this through.
