### ISSUE TITLE
'Cloud Code Webhooks' documentation seems to have been removed. 

### ISSUE THREAD

**Issue by apersaud** [ParsePlatform/Docs#386]
The open-source Parse-Server (v 2.19+) supports Cloud Code Webhooks, whose feature allows you to register an external server to handle hook triggers and functions. The documentation used to be available at [Cloud Code Guide](http://parseplatform.github.io/docs/cloudcode/guide/#cloud-code-advanced-cloud-function-webhooks), but it seems to have been recently removed.

The original version of the `Advanced Cloud Code` with the `Cloud Code Webhooks` section can be found here: [Original Version](https://web.archive.org/web/20160715105814/https://parse.com/docs/cloudcode/guide#cloud-code-advanced-cloud-code-webhooks). The documentation is important for users to who want to implement a Parse Cloud Code Webhook application, since it describes the protocol format that the server expects. (We use it with our framework [Parse-Stack](https://github.com/modernistik/parse-stack), which helps us make sure we are compatible).

Since the open-source Parse-Server supports this feature, any reason why the documentation was removed, or has it been moved to a new location?

Thanks!

**Comment by hramos** [comment]
The webhook docs were removed a few months ago because Parse Server didn't support the feature. We can re-add them back to the docs, feel free to send a PR.

**Comment by heresmyinfo** [comment]
I'm confused - does the latest version of Parse support Webhooks now?

**Comment by apersaud** [comment]
The latest version of the Parse-Server does support webhooks just like the Parse hosted system. Both triggers (beforeSave, afterSave, etc.) and functions are supported.

**Comment by lewisloofis** [comment]
Hello, so is webhook still available? I'm checking the changelog and parse-server files but doesn't see changelog related with webhook, but in Parse Dashboard webhook looks available.

**Comment by flovilmart** [comment]
Webhooks are still available and fully functioning, they are also integrated in the JS SDK if you wanna register your web hook programatically https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseHooks.js

**Comment by lewisloofis** [comment]
Oh I see, so that means the docs is outdated, thanks then. Any plans to update the docs related with it? I'm exploring Parse Server as a possible new tool so it will be helpful for me or new users to parse-server.

**Comment by flovilmart** [comment]
I'll check if we can revert the docs for web hooks, otherwise, you can use cloud code hooks (this is what we do) to reduce the HTTP overheads of calling remote webhooks

**Comment by flovilmart** [comment]
@lewisloofis @apersaud the original file is there: https://github.com/parse-community/docs/commit/d36593621bb4e55bb8f7730f3147ff3c2561e582#diff-ade435dfbdc65f7e29e71e364375e934 Do you wanna make a PR for re-introducing those?

**Comment by lewisloofis** [comment]
Never do PRs before, would be interested if I know how. Do I only need to add Cloud Code Webhook part only?

**Comment by flovilmart** [comment]
probably, let me know if you need anything, otherwise, I can probably take care of it later this week.

**Comment by lewisloofis** [comment]
I've tried to do pull request at #469. Please check

**Comment by lewisloofis** [comment]
Feels nice for my first PR. Btw do you have any use case about this Cloud Code Webhook feature, especially the Function Webhook? At first glance I think it's for sending POST request to another service (for example if I create another outside API), but it seems the POST request is sending specific object spec to my URL and I cannot customize what I sent to other URL.
