### ISSUE TITLE
Parse Ruby SDK for Community Highlights

### ISSUE THREAD

**Issue by apersaud** [ParsePlatform/Docs#392]
Hi everyone,

We've worked on creating and open sourcing a highly compatible Parse Server Ruby SDK and ORM: https://github.com/modernistik/parse-stack . What would be the process of having this be reviewed and maybe added to the list of Community Highlights in the documentation (https://parseplatform.github.io/#community)?

Thanks

**Comment by flovilmart** [comment]
Can you open a pull request on https://github.com/parse-community/parse-community.github.io, Thanks!

**Comment by apersaud** [comment]
Thanks. I went ahead and opened a pull-request with the changes:

https://github.com/parse-community/parse-community.github.io/pull/1
