### ISSUE TITLE
Client Class Creation in Doc

### ISSUE THREAD

**Issue by HaveF** [ParsePlatform/Docs#393]
[docs/compatibility.md at gh-pages · ParsePlatform/docs](https://github.com/ParsePlatform/docs/blob/gh-pages/_includes/parse-server/compatibility.md#client-class-creation)

This feature is implement by this PR: [Add allowClientClassCreation option by Marco129 · Pull Request #684 · ParsePlatform/parse-server](https://github.com/ParsePlatform/parse-server/pull/684/files)

Remove this?

**Comment by flovilmart** [comment]
Updates the page, thanks for pointing that out! (https://github.com/parse-community/docs/commit/2107cfb0b35f2fd34c0dda23ea0c802c52bd1af6#diff-5d1017abf41610ae48c81919c5a7ddad)
