### ISSUE TITLE
The argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by jabina** [ParsePlatform/Docs#394]
I am getting the error in below line in Swift3. Can anyone help me out? 

var result = query?.run(&error)

The below is my code...

            let database = CBObjects.sharedInstance().database
            let query = database?.viewNamed("sampleview").createQuery()
            query?.startKey = "m"
            
            var error: NSError?
            **var result = query?.run(&error)**
            while let row = result?.nextRow() {
            }

**Comment by flovilmart** [comment]
in swift 3 I believe error handling has changed:

``` 
var result = try? query?.run()
```

**Comment by jabina** [comment]
Thank you very much for your reply. it works

**Comment by jabina** [comment]
Hi
can anyone help me out how to parse each row in CBLQuery?

this is my code
 let results = try? query?.run()            
            while let row = results!?.nextRow() {
                if row.document!.properties != nil {              
                }
            }
