### ISSUE TITLE
[JS] Sessions pointing to Users

### ISSUE THREAD

**Issue by g3r4n** [ParsePlatform/Docs#400]
![parsedoc](https://cloud.githubusercontent.com/assets/10941033/22323741/9960fad0-e3f0-11e6-80fe-5ecb504eb446.jpeg)
Sessions part is pointing to Users part in the left Menu

**Comment by hramos** [comment]
I'm going to leave this one up for grabs.

**Comment by flovilmart** [comment]
Those links should be fixed now.
