### ISSUE TITLE
What is parse? (Should be a top level question)

### ISSUE THREAD

**Issue by ichiro101** [ParsePlatform/Docs#402]
I can't find information on what parse fundamentally is and what it is supposed to do in the docs, and it makes no mention to why I should use it. Is it answered anywhere in the docs?

**Comment by hramos** [comment]
This is one of the hardest problems in startup world :) This is usually covered in a marketing site, which used to be parse.com but we just spun that down yesterday.

Give us some time to finish up the shutdown and I will see what I can do to restore some of the marketing site to the open source GitHub page at parseplatform.github.io.

**Comment by flovilmart** [comment]
@hramos we could very well add something relevant on all repos README (https://github.com/fastlane/fastlane#fastlane)

**Comment by TomWFox** [comment]
I've added an issue in the Parse Platform website repo [#18](https://github.com/parse-community/parse-community.github.io/issues/18) which seems a more relevant place than docs as these questions should be answered at the top level, not in the docs of individual libraries.
