### ISSUE TITLE
docs for js doesn't correspond the repo

### ISSUE THREAD

**Issue by jaimeagudo** [ParsePlatform/Docs#404]
Basically https://parseplatform.github.io/docs/js/guide/ doesn't match

https://github.com/parseplatform/docs/tree/gh-pages/_includes/js

besides the footer link saying *Want to contribute to this doc? Edit this section.* 

The broken linkage leads to loads of confusion and there are key deprecations like

```
Parse.Cloud.useMasterKey is deprecated (and has no effect anymore) on parse-server, please refer to the cloud code migration notes: https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse#cloud-code
```
That are not stated clearly on the public guide 

I am happy to help with some guidance

**Comment by flovilmart** [comment]
All links should be OK now, feel free to open a new issue if it persists.
