### ISSUE TITLE
www.parsecdn.com times out

### ISSUE THREAD

**Issue by parkr** [ParsePlatform/Docs#413]
Hey,

I was just trying to load http://parseplatform.github.io (not this repo, I see, but there doesn't seem to be a public source for parseplatform.github.io, so I figured I'd open an issue here 😄 ) and I get a big blank white screen for about thirty seconds before anything shows up.

It seems accessing the following JavaScript resource timed out for me:

```text
https://www.parsecdn.com/js/parse-1.6.7.min.js
```

According to the Chrome Network Inspector, this resource was `Stalled` for 27.82s. Accessing it directly also times out.

It seems the link is outdated, or the CDN service is disrupted/shut down. Can you confirm either of these things for me?

/cc @hramos @lacker

**Comment by hramos** [comment]
www.parsecdn.com no longer serves content, we should remove that resource. This is served from a private repo, I'll send a PR today.

**Comment by parkr** [comment]
Thank you, @hramos!

**Comment by hramos** [comment]
Resolved.
