### ISSUE TITLE
[JS] FB-init code not rendered but executed

### ISSUE THREAD

**Issue by pzoechner** [ParsePlatform/Docs#415]
In the Parse-JS docs under [Facebook Users: Setup](https://parseplatform.github.io/docs/js/guide/#setup) browsers won't show the code as the `<script>`-tag is not properly escaped. It even results in console log errors.

I escaped the `<script>` and `</script>` with special entities: `&lt;script&gt;`

My fix: https://github.com/ParsePlatform/docs/compare/gh-pages...pzoechner:patch-1

**Comment by hramos** [comment]
Can you open a PR?
