### ISSUE TITLE
How to add data to parse relation column in parse dashboard (Programatically)?

### ISSUE THREAD

**Issue by sandeep2242** [ParsePlatform/Docs#434]
Suppose i am having a column in parse dashboard named "vendorInv" of "Vendors" class which is a parse relation pointing to class "VendorInv".
Now i can add data to parse relation in parse dashboard.
But the problem is I am unable to add data to relation column programatically in android (below is my tried snippet ).
Any help would be greatly appreciated.
`` ParseObject productDetails = new ParseObject("VendorInv");

            productDetails.put("productMrp", 1337 + "Rs");
            productDetails.put("productName", "Rbk");
            productDetails.put("productDetails", "sjhkfdasfuafhkajfh");
            productDetails.put("size", "xl");
          

            ParseObject pd = ParseObject.createWithoutData("Vendors", objId);

            /*ParseRelation<ParseObject> pr = pd.getRelation("vendorInv");

            pr.add(productDetails);*/

            pd.add("vendorInv",productDetails);
            /*pd.put("vendorInv", productDetails);*/

            pd.saveInBackground(new SaveCallback() {
                @Override
                public void done(ParseException e) {
                    if (e == null) {
                        Log.i("Parse", "Save Succeeded");
                    } else {
                        Log.i("Parse", e.toString());
                    }
                }
            });`

error: Parse: com.parse.ParseException: java.lang.IllegalStateException: unable to encode an association with an unsaved ParseObject`

**Comment by flovilmart** [comment]
You need to save your `productDetails` first and then, add it to the relation `pd.add("vendorInv",productDetails);` , finally, save your `pd` object with `pd.saveInBackground...`
