### ISSUE TITLE
Relations Sections Defaulting to JS

### ISSUE THREAD

**Issue by montymxb** [ParsePlatform/Docs#442]
A user brought up an [issue](https://github.com/parse-community/parse-php-sdk/issues/321) with the docs regarding the php sdk. After taking a look I noted that it appears _all_ the sdks exhibit the same issue. In such sections as 'Relations' the code samples appear to be defaulting to JS where there are multiple samples to choose from.

An example of this can be seen in the [php guide](http://docs.parseplatform.org/php/guide/#using-pointers), the [ios guide](http://docs.parseplatform.org/ios/guide/#using-pointers) and the [android guide](http://docs.parseplatform.org/android/guide/#using-pointers). It looks like the issue stems from shared files in the `_includes/common`, where multiple languages may be conditionally displayed with the same documentation, using expressions such as `{: .common-lang-block .php }`.

I'm not certain but taking a quick look this appears to be stemming within the javascript which dynamically displays the appropriate code sections. I'm not too familiar with this project but if no one else is sure I can take a look at rectifying this issue myself.

**Comment by flovilmart** [comment]
It seems to be all good! Great job!

**Comment by montymxb** [comment]
Excellent! Glad to hear it
