### ISSUE TITLE
Should bundle.js and Gemfile.lock changes be committed

### ISSUE THREAD

**Issue by addisonElliott** [ParsePlatform/Docs#462]
I am interested in contributing to this community but while setting up the docs, there were some changes caused by running bundle install.

The two files changes are:
- Gemfile.lock
- assets/js/bundle.js

I am building on Windows 10 64-bit.

The diff file can be found here: https://github.com/addisonElliott/docs/commit/ef2aa9f5d855f0083bfbe4fa214b66ef321e8f34 

In the Gemfile lock, most of the changes are updating version but there are two Windows-only changes that should not be committed.
- There is a specific nokogiri port for Windows: nokogiri (1.8.0-x64-mingw32)
- Also, the additional platform x64-mingw32 was added which is Windows only.

For the bundle.js file, these changes are fine but what happens if another person tries to contribute code and they are using a different version of bundle that reverts these changes?

# My Proposed Solution
The two files are added to .gitignore and removed from the repository. These will be auto generated each time someone builds the docs.

**Comment by flovilmart** [comment]
> The two files are added to .gitignore and removed from the repository. These will be auto generated each time someone builds the docs.

This is not acceptable as Gemfile.lock should be commited to the repo so everyone shares the same versions of the gem dependencies.
