### ISSUE TITLE
[Android] Improve docs for push

### ISSUE THREAD

**Issue by natario1** [ParsePlatform/Docs#473]
Commited some internal changes to Android regarding push handling, mostly

parse-community/Parse-SDK-Android#732
parse-community/Parse-SDK-Android#735

Docs could mention this. For instance, PPNS is not supported anymore, and from Android Oreo onwards, developers don't need to register a `PushService` in their manifest.

**Comment by iernie** [comment]
Sorry to ask this in the issue, but just to be sure, you still need `PushService` in the manifest if you want to override any of the push functions like notificationChannel?

**Comment by natario1** [comment]
@iernie these functions are in `ParsePushBroadcastReceiver` so nothing changed.

Just to clarify, PushService is still needed if your app minSdk is < 26. If you support *only Oreo* and nothing below, you *can* remove PushService. But this will not be relevant for a few years I guess

**Comment by natario1** [comment]
And, by the way, we need docs for `ParsePushBroadcastReceiver` changes too

**Comment by iernie** [comment]
@natario1 Ahh thanks for the clarification :)

**Comment by rogerhu** [comment]
can we update these docs?

**Comment by rogerhu** [comment]
Because PushServiceApi26 is now added, we need to yank PushService out of AndroidManifest.xml. 
 Otherwise I'm seeing redundant handling happening.

https://github.com/parse-community/docs/blob/0bd1f8847788ecf321da5cd26e5f2ef4117ec48c/_includes/parse-server/push-notifications-android.md 

https://github.com/parse-community/docs/pull/474

**Comment by natario1** [comment]
@rogerhu But `PushService` is still needed for API 1-25? What kind of issues are you seeing?

https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/PushServiceUtils.java

**Comment by Jawnnypoo** [comment]
Can probably close this one out now 😄

**Comment by TomWFox** [comment]
Is this relevant anymore, if not I’ll close.

**Comment by Jawnnypoo** [comment]
Yep, you can close this.
