### ISSUE TITLE
Restore Tasks Section in Unity Guide

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Docs#48]
The Task section of the Unity SDK Docs is missing:
https://parse.com/docs/unity/guide#tasks

**Comment by BenWoodford** [comment]
Similarly all the examples that use tasks are using the .NET snippets, aka using await and async which we don't have the pleasure of using in Unity.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by hallucinogen** [comment]
@BenWoodford can you make another issue and assign it to me?

IIRC, Task section was purposely deleted from our Unity SDK Docs since we (and Unity) don't officially support `System.Threading.Tasks`. I'll revisit this soon.
