### ISSUE TITLE
Full Text Search iOS SDK

### ISSUE THREAD

**Issue by DIMEGLIOM** [ParsePlatform/Docs#480]
Full text search was implemented recently, can someone add documentation regarding how to use this feature within iOS?

**Comment by flovilmart** [comment]
@dplewis can we do something about it?

**Comment by dplewis** [comment]
@flovilmart I opened 
https://github.com/parse-community/docs/pull/498 a while ago that includes documentation for this issue. Just waiting on someone that knows swift to finish it off.

**Comment by flovilmart** [comment]
Ah someone like me then :p

**Comment by dplewis** [comment]
Exactly!!!
