### ISSUE TITLE
Android API Reference Outdated

### ISSUE THREAD

**Issue by addisonElliott** [ParsePlatform/Docs#486]
The [http://parseplatform.org/Parse-SDK-Android/api/](API reference) for Android is a bit out of date. I was working on client interceptors in August and it was outdated then as well.

How often does this get generated?

I'm wondering if there isn't a better way to have this done automatically?

**Comment by addisonElliott** [comment]
I did some more research on this and I have an idea of what may be better.

There is a website named http://javadoc.io that hosts JavaDoc files that are published to Maven central. 

The last JavaDoc published for Parse on Maven was 1.15.5. Here is the link for it: http://www.javadoc.io/doc/com.parse/parse-android/1.15.5

However, there have not been JavaDocs posted for the past revisions until then. I think it would be easy to point the API link to the javadoc.io.

Another **great** thing about the website is that it has a header at the top to select what version you want to view the docs for!

@flovilmart What are your thoughts?

**Comment by flovilmart** [comment]
the docs are part of each repository, on either the docs folder or the gh-pages branch. We also have out dated docs on iOS, JS etc... as the docs builds were not part of the transition, unfortunately. Going forward, I don'T really mind.

For iOS, I have a proper script for building docs with Jazzy, that I need to package/deploy into the CI so we can push them upon tags. Cocoapods also host the docs as part of Cocoadocs.

As for Android, I have no idea, I'm open to suggestions / solutions that are properly integrated with the workflow, and reduce the amount of work for maintainers and contributors.

**Comment by addisonElliott** [comment]
Okay, when I get some time I will look into this more. I'm not sure how the Android docs are currently hosted honestly. I can't find it in the docs repository.

If we can simply get the javadoc (documentation)'s uploaded to Maven each time a new Android version is released, then I think my idea can work pretty easily with minimal changes.

Take a look at what I mean. There are no javadoc doc's for the past revisions.
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.parse%22%20AND%20a%3A%22parse-android%22

**Comment by addisonElliott** [comment]
Solved with https://github.com/parse-community/Parse-SDK-Android/pull/801
