### ISSUE TITLE
Unclear auth configuration object

### ISSUE THREAD

**Issue by lewisloofis** [ParsePlatform/Docs#492]
Hello,

Sorry for double posting issue, I'm writing this on phone and accidentally hit submit. You can delete my previous issue at #491

Anyway I want to know about the `auth` option object in parse server. The documentation say about supporting facebook, linkedin, google, twitter, etc. But the documentation seems to be unclear about the objects parameter for each supported auth (for example what key value I should define for google or linkedIn auth). May I know what values are used for each of these sipported providers? It will be a big help for setting authentications

**Comment by montymxb** [comment]
Whoops, opened and closed the existing post by accident 😆 . You're all good though, thanks for letting us know that was a mistake.

The auth configuration varies per provider. We should have details regarding what data is required per provider however. If this is not present in the docs this is something we should consider clarifying with a PR.

Could you also indicate which section of the docs you were looking in? Just so we know which doc you're referring to.

**Comment by lewisloofis** [comment]
I want to know about the Google and Facebook auth properties specifically, but from the docs it looks like there are other accounts support (like LinkedIn or Instagram). Knowing these properties may help, since I can consider using other oauths if the needs are there.

Here is the [link](http://docs.parseplatform.org/parse-server/guide/#oauth-and-3rd-party-authentication)

**Comment by montymxb** [comment]
There are quite a few others actually, you can see them by name [here](https://github.com/parse-community/parse-server/tree/master/src/Adapters/Auth). It does look like we have quite a few undocumented auth options that have been added over time.

I'm currently focusing on the .NET sdk, so I won't be able to get to this atm. I believe a PR clarifying all available 3rd party auths with configurations detailed would be awesome. If you're up for it you can put together a PR, or anyone else who has a moment. In the future I'll have to make some time for this if it's not taken care of by then.

**Comment by flovilmart** [comment]
I’ll update the docs tomorrow with all required infos about auth for the supported providers

**Comment by flovilmart** [comment]
@lewisloofis can you have a look at the PR #494 and let me know if it's good for you? Most of the auth data adapters don't require a configuration.
