### ISSUE TITLE
new link to wiki - community links

### ISSUE THREAD

**Issue by iteco** [ParsePlatform/Docs#508]
I wanted to try out Parse on plain Ubuntu 16.04, but i didn't find a guide for it from your wiki page (https://github.com/parse-community/parse-server/wiki) or with google.

I used then instructions for ubuntu 14.04, but there were many issues/1/ and I decided to make an updated version.

Updated version is here: https://iteco.fi/run-parse-server-ubuntu-16-04/

If you see that it brings some value, feel free to add it to the parse-server's wiki page.
--
/1/ Issues briefly
* mongodb version what was mentioned in guide for 14.04 was not available anymore
* mongodb release key was changed
* nodejs installation was also pointing to old version
* it is missing instructions to install 'libkrb5-dev' (causes error) 

Compared to that 14.04 guide I have added also following sections, which i think that are very useful.
* parse-dashboard
* pm2

![selection_227](https://user-images.githubusercontent.com/4575046/37118181-09df47ee-225c-11e8-966e-a83af46e4789.jpg)

**Comment by montymxb** [comment]
Hey @iteco , I haven't looked at this personally but can anyone back this guide for an updated setup? @parse-community/core-maintainers if any of you guys are setting up on 16.04 and can provide some input I would be much obliged 😄 .

The one thing I noticed was that this uses the old parse-server-example repo, which we're _definitely_ moving away from. I would recommend following the setup from npm or via the install script mentioned in the [docs](http://docs.parseplatform.org/parse-server/guide/#getting-started) (it's a bit below the Getting Started section).

**Comment by iteco** [comment]
I am also interested in hearing taking feedback from the guide, and fix my installation and instructions at the same time.

Regarding old parse-server-example repo usage in the linked guide. I can change that in the guide to use the install script used in the docs, if you want to include the guide to the community links.  Otherways I guess that there isn't much point for doing it as my installation is running just fine. :)

then one other point.. in the original Digital Ocean guide and in the referred docs/installation script there is used normal mongodb, but later in the docs is recommend to use MongoRocks, which should be installed from the different place (after I have already installed and set up everything..!). Is that MongoRocks some old stuff or still the recomended db ?

**Comment by TomWFox** [comment]
If this guide is still up to date and you still want it added to the parse server repo, I think you should make a new issue there and close this one.

Alternatively you could add this as a topic on the new [community forum](https://community.parseplatform.org).
