### ISSUE TITLE
Translate documentation to Spanish

### ISSUE THREAD

**Issue by rafaecheve** [ParsePlatform/Docs#51]

**Comment by rafaecheve** [comment]
I can help :)

**Comment by hramos** [comment]
Y yo puedo revisar cualquier pull request que abras :)

**Comment by rafaecheve** [comment]
Muchas Gracias, voy a completar la documentación  para iOS para comenzar

**Comment by hramos** [comment]
Linking #97 here.

**Comment by rafaecheve** [comment]
typos fixes added to #97

**Comment by hramos** [comment]
Update: most of the iOS documentation has been translated. We still need translations for the rest of the platforms before support for Spanish can be added to our Docs.
