### ISSUE TITLE
Remove "dashboard" documentation

### ISSUE THREAD

**Issue by neelkamath** [ParsePlatform/Docs#517]
The REST API docs have references to using the dashboard all over. I thought the dashboard was inaccessible now that Parse has been shut down from Facebook's end.
Here's an extract from the Android docs speaking of a "Settings page":

> You may request a cleanup of unused files in your app’s Settings page. Keep in mind that doing so may break functionality which depended on accessing unreferenced files through their URL property.

**Comment by addisonElliott** [comment]
The dashboard is open-source on GitHub and available for use. https://github.com/parse-community/parse-dashboard

It's been awhile since I've looked at it, but to "request a cleanup of unused files" sounds odd. A request to me sounds like someone is going to review it, but with you being the server administrator, then there really is no one to review. Sounds like a remnant of when Facebook owned and when they would review them manually?

**Comment by neelkamath** [comment]
Exactly, I was stuck on that for a while. I thought there was a spec of some sorts that Parse on Buddy and the others were meant to implement or something. Should I close this issue then?

**Comment by addisonElliott** [comment]
One idea is to include some information in the documentation about using parse-dashboard? I'm not sure if there's a link or any discussion about it in the docs.

**Comment by neelkamath** [comment]
Yea. Ever since Facebook deprecated it, there's no telling of the server or anything. I believe on the [homepage](http://docs.parseplatform.org/) there should be a link to the server and dashboard and optionally some third party services like Parse on Buddy.
Also, I'm pretty sure the macOS and iOS docs are 100% the same. Not only is there an iOS but no macOS doc folder in the repo, but the following two files are the exact same (save for replacing iOS with macOS): 
[macOS](https://github.com/parse-community/docs/blob/775d1ba8e7773b59b01997eb5ec7d4484e154789/macos.md)
[iOS](https://github.com/parse-community/docs/blob/c471b4e0c2dfbbd68a1157cbd9c5fe50cdc1ebcd/ios.md)
You can open them in side by side tabs viewing the "Raw" file to see what I mean more easily.

**Comment by neelkamath** [comment]
Also, on the top-right of the docs home page are two links. One pointing to the homepage itself and another to the blog which has been removed. There are a bunch of links pointing to the dead blog as shown [here](https://github.com/parse-community/docs/search?utf8=%E2%9C%93&q=blog.parse.com&type=).
