### ISSUE TITLE
Link header bug

### ISSUE THREAD

**Issue by neelkamath** [ParsePlatform/Docs#518]
Take [these Android docs](http://docs.parseplatform.org/android/guide/#parcelable) for example, when you click on the `Parcelable` subsection of `Files` it goes all the way up to the `Parcelable` subsection of `Objects` because they have the same name and `Objects` is higher up on the page. Either the pages formatting the docs should be changed or the name of the subsections if they clash.

**Comment by addisonElliott** [comment]
Good call. I'm willing to bet this issue occurs on just about every platform since the sections change by little.

I'm surprised this isn't handled by Jekyll on it's own.

**Comment by flovilmart** [comment]
This is the automatic link generation + menu generator. It doesn’t create url’s Based on the full path but only the current heading name. 

My recommendation for now is to rename the conflicting section headers

**Comment by neelkamath** [comment]
Shall I submit a PR for all platforms or are you already on it?

**Comment by flovilmart** [comment]
Go ahead!
