### ISSUE TITLE
Document that Parse cannot handle $ and . in object keys

### ISSUE THREAD

**Issue by mrclay** [ParsePlatform/Docs#524]
In my first Parse project we ran into INVALID_NESTED_KEY errors in numerous places and this key name limitation is only documented in the error message.

**Comment by flovilmart** [comment]
This is expected, . And $ are restricted operators.

**Comment by mrclay** [comment]
I think it's already documented under the heading "Data" somewhere.

**Comment by flovilmart** [comment]
Yep: http://docs.parseplatform.org/rest/guide/#data-storage
