### ISSUE TITLE
Force HTTPS 🔒

### ISSUE THREAD

**Issue by theel0ja** [ParsePlatform/Docs#532]
https://docs.parseplatform.org/

It works with HTTPS since GitHub introduced HTTPS for custom domains.

**Comment by flovilmart** [comment]
Yes! Anything we should do?

**Comment by theel0ja** [comment]
Force HTTPS on the settings and fix HTTP references and mixed content warnings.

(you should enable HTTPS for the main site, too)

More information: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by flovilmart** [comment]
Any chance you wanna open a Pr for this?

**Comment by flovilmart** [comment]
This should be done now.
