### ISSUE TITLE
Search docs not woking

### ISSUE THREAD

**Issue by thobhanifreddy** [ParsePlatform/Docs#544]
Search features looks broken. Whatever I search it shows me "No result found for query"

![screen shot 2018-07-28 at 16 28 43](https://user-images.githubusercontent.com/12369649/43355907-7f20ccf2-9283-11e8-9dd4-10501189cd22.png)

I have tried various combination of words in cloud code and js docs but no luck.

**Comment by flovilmart** [comment]
WE need to have a look at the algolia plugin! Thanks for reporting it

**Comment by thobhanifreddy** [comment]
Looks like this issue is solved! 
https://github.com/parse-community/docs/commit/271ca12fe5039862c0e60d5031c00a97c079993c
