### ISSUE TITLE
JS API doc: link to v2 migration guide is broken

### ISSUE THREAD

**Issue by Eyesiah** [ParsePlatform/Docs#553]
The JS API docs at http://parseplatform.org/Parse-SDK-JS/api/v2.0.1/ have a section "Upgrading to Parse SDK 2.0.0" that links to a migration guide at http://parseplatform.org/Parse-SDK-JS/api/v2.0.1/2.0.0.md . However, that link doesn't work.

A working URL is https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md

**Comment by flovilmart** [comment]
Can you open a PR please? I have no idea where this link is located.

**Comment by flovilmart** [comment]
Closing as the issue is on the JS SDK README.md file
