### ISSUE TITLE
Cloud Code doc update  

### ISSUE THREAD

**Issue by thobhanifreddy** [ParsePlatform/Docs#556]
Since parse-server v3, cloud code no longer uses callbacks. So we need to update docs accordingly. 

But there are many people out there using older version of parse-server. So not sure how should we update it.

**Comment by flovilmart** [comment]
Feel free to get started on this.

**Comment by acinader** [comment]
I'm gonna close this as too general.  I read through the cloud code just now and I see no obviously wrong code examples.
