### ISSUE TITLE
📙 Probably there is no Int() function or class 

### ISSUE THREAD

**Issue by sakhunzai** [ParsePlatform/Docs#569]
I think there ambiguity in [silent push notification](https://docs.parseplatform.org/parse-server/guide/#silent-notifications) docs, when its says **Int(1)** , actually it means 1 not "1" and I suspect there is any function/class or library (as per my knowledge) named **Int**.  A better wording could have been **Number(1)** , instead of **Int(1).** Please correct me if I am wrong.

**Comment by flovilmart** [comment]
If you consider only Javascript yes, but other languages may have an Int() functions. We wanted to explicitely mention that is should not be a string

**Comment by sakhunzai** [comment]
yes I mean Javascript. If Int() is not a common function across all language/platforms then it seems reasonable to replace it with meaningful alternative which is common or add more details, just a humble opinion.

**Comment by flovilmart** [comment]
Feel free to open a PR and propose a change then

**Comment by sakhunzai** [comment]
#570 Done
