### ISSUE TITLE
📙 Remove unneeded references to Parse.com

### ISSUE THREAD

**Issue by TomWFox** [ParsePlatform/Docs#619]
__Link to section:__
Dotted throughout all the guides in different sections.

__What is the issue?__
There are still lots of references in the docs to Parse.com or explanations that use language that imply use on the hosted Parse Cloud which no longer exists.

e.g.

The [sending pushes](https://docs.parseplatform.org/js/guide/#sending-pushes) section in the JS guide...
> Sending notifications is often done from the Parse.com push console

__Can you propose a solution?__

As appropriate references should be removed or adjusted to language that is correct for Parse Server.

e.g.
> Sending notifications is often done from the Parse Dashboard push console

instead of...
> Sending notifications is often done from the Parse.com push console

**Comment by TomWFox** [comment]
Any reason to keep the section on compatibility with parse.com in the Parse Server guide? @acinader

**Comment by acinader** [comment]
what do you think?

**Comment by TomWFox** [comment]
@acinader Well at this point there shouldn’t really be anyone migrating from a project previously hosted on parse.com.

However there are some useful bits i.e the bit on email verification that aren't included elsewhere - although email verification is mentioned on the documentation on the Parse Server readme.

To me it would make sense to remove it and add any useful bits elsewhere.

**Comment by TomWFox** [comment]
Also is there a particular reason to have some documentation in the parse server readme and some on the docs guide, seems to be doubling up for no reason to me?
