### ISSUE TITLE
Add JavaScript, Java, and C# examples to Relations Guide

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Docs#62]
The Relations Guide only has Objective-C examples. We'll need JavaScript, Java, and .NET examples to be added.

**Comment by nakp** [comment]
One to one relations examples are missing for iOS as well

**Comment by hramos** [comment]
Which section are you referring to?

**Comment by nakp** [comment]
Seems like [Relations](https://parse.com/docs/ios/guide#relations) is not even un this repo

**Comment by hramos** [comment]
That would be https://github.com/ParsePlatform/Docs/blob/master/en/common/relations.mdown

**Comment by hramos** [comment]
I found a cached version of the previous Relations guide and it didn't have any code examples under One-to-one. It was simply missing two bullet points which I've now added.

**Comment by nakp** [comment]
Oh, I missed that one, and yes, the online documentation was lacking of those examples, thank you!
