### ISSUE TITLE
📕 Add documentation for Parse.Cloud.afterFind

### ISSUE THREAD

**Issue by nangyal** [ParsePlatform/Docs#627]
__Link to section:__
https://github.com/parse-community/parse-server/blob/master/src/cloud-code/Parse.Cloud.js#L275

__What is the issue?__
 Parse.Cloud.afterFind not documented

__Can you propose a solution?__

**Comment by TomWFox** [comment]
Thanks for bringing that up, would you be willing to make a PR for this?
