### ISSUE TITLE
📕 Parse.Cloud.onLiveQueryEvent not documented

### ISSUE THREAD

**Issue by nangyal** [ParsePlatform/Docs#628]
__Link to section:__
https://github.com/parse-community/parse-server/blob/master/src/cloud-code/Parse.Cloud.js#L290

__What is the issue?__
Parse.Cloud.onLiveQueryEvent  not documented

__Can you propose a solution?__
https://stackoverflow.com/questions/43708317/detect-livequery-connected-clients-on-parse-server

**Comment by TomWFox** [comment]
Would you be willing to open a PR for this?
