### ISSUE TITLE
📕 Add documentation for query exclude keys

### ISSUE THREAD

**Issue by TomWFox** [ParsePlatform/Docs#632]
See parse-community/parse-server#5737 for the server implementation.
See parse-community/parse-sdk-js#857 for the JS SDK implementation.
See parse-community/parse-php-sdk#445 for the PHP SDK implementation.

**Comment by TomWFox** [comment]
@RaschidJFR would you like to take a stab at the documentation?

**Comment by RaschidJFR** [comment]
Sure thing. If you don't mind, I'll have a look at this next week as I currently got a high work load. The documentation to update should be the REST guide, right?

**Comment by TomWFox** [comment]
If you can, both the REST and JS guides will need updating. No huge rush, some features go undocumented for months so a week or so won't do any harm.

**Comment by RaschidJFR** [comment]
So I've sent my PR for the REST guide.
For the JS guide, is there any particular part you know is missing documentation?

**Comment by dplewis** [comment]
@RaschidJFR can you also do the PHP docs? If not I can build on your PR.

**Comment by RaschidJFR** [comment]
Sorry, I’m not familiar with the PHP SDK :/
Anything else on the JS?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dplewis** [comment]
An example of `query.exclude(...)`  should be enough
