### ISSUE TITLE
🐛  Website is down

### ISSUE THREAD

**Issue by jamlfy** [ParsePlatform/Docs#640]
**Describe the bug**
Simple enter to `http://parseplatform.org/`

**To Reproduce**
1. Go to 'browser'
2. Go to the web  `http://parseplatform.org/`
3. Look a 404!!

**Screenshots**
* https://www.dropbox.com/s/71yzqsiu09fl2nx/Captura%20de%20pantalla%202019-07-13%2017.24.50.png?dl=0

**Desktop (please complete the following information):**
 - Browser

**Comment by TomWFox** [comment]
Thanks for reporting this, I've been having a few issues but the docs website is back up now
