### ISSUE TITLE
🐛 iOS SDK Guide language selection broken for examples

### ISSUE THREAD

**Issue by ian-bradbury** [ParsePlatform/Docs#643]
Within the iOS SDK guide example code is provided in Objc and Swift.  Unfortunately only the Objc example code displays.  If you select the Swift language - nothing happens, the example code is not updated.

Checking the browser console I can see the following error message.
<img width="562" alt="Screenshot 2019-07-14 at 21 03 32" src="https://user-images.githubusercontent.com/13846268/61188686-e766b680-a67a-11e9-8a64-333894aa3257.png">
Unfortunately my JS skills are <cough /> worse than poor.

I can see that the bundle.js file was updated only 2 days ago - I guess something in that update has caused this error.

**To Reproduce**
1. Go to https://docs.parseplatform.org/ios/guide/#getting-started
2. Scroll down to 'Saving Objects'
3. Click the SWIFT example button

**Expected behavior**
the example code should update to display the Swift example code.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS / 10.14/ Mojave
 - Safari, Firefox, Chrome

**Comment by TomWFox** [comment]
Thanks for that detailed report, I've put together a quick fix #641, feel free to test it.

**Comment by TomWFox** [comment]
Just checked on the live site and it's working now. If it's not for you try removing the browser cache and refreshing.
