### ISSUE TITLE
📕 Is this API doc for ParseLiveQuery-iOS-OSX referenced anywhere?

### ISSUE THREAD

**Issue by noobs2ninjas** [ParsePlatform/Docs#651]
__References:__
I ran into this old [Parse Live Query API Doc](http://parseplatform.org/ParseLiveQuery-iOS-OSX/index.html) for iOS/OSX. Unless I'm just blind I can't seem to find a single place on the parse platform site. Seems a bit behind but I never even knew it was out there. 
__Proposed solution:__
Let's see if we can get it linked somewhere. I'll definitely be updating the repos README to link it at least.

**Comment by TomWFox** [comment]
I think you’re right about it not being referenced, I wasn’t aware of it. As there is no guide for live query I don’t think it would make sense to reference the api doc on the website (unless we decide to add a guide). Adding a reference in the readme is a good idea, we could also add a section called live query (under queries) in the iOS docs that gives a brief explanation and links to the readme and the api doc.

**Comment by noobs2ninjas** [comment]
I agree. ParseLiveQuery I found out yesterday has a lot of work that needs to get done. Basically none of the callback functions work. So, I'll just add this in with it. In terms of docs since I'm working on those anyway I might just drop a quick mention and link to the LiveQuery repository itself and as well as in the iOS API documentation. 

On a side note. It would seem strange to me that this would exist for ParseLiveQuery but not for ParseUI. I'll do some snooping in the source to see if I can find it.

**Comment by noobs2ninjas** [comment]
NM your request was about ParseUI docs not the API page. How are all the API docs done?

**Comment by TomWFox** [comment]
No, that is actually another issue #596 - the links from the iOS guide to the ParseUI API doc 404 - I think it's related to how the jazzy docs are generated - it's not doing the ParseUI subfolder - If you can work out how to fix that please send a PR to the iOS repo 😉

**Comment by noobs2ninjas** [comment]
Ill take a look. 

I'm actually trying to fix ParseLiveQuery right now. So I may just write the docs since I'm also working on rewriting all the Parse docs. Speaking of ParseLiveQuery. Could you read [this](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues/196) issue and give me your opinion.

We can close this issue I think since I'll just be writing the doc and doing the readme edits.
