### ISSUE TITLE
📕Microsoft Graph Auth

### ISSUE THREAD

**Issue by TomWFox** [ParsePlatform/Docs#692]
__References:__
parse-community/parse-server#6051
__Proposed solution:__
https://docs.parseplatform.org/parse-server/guide/#oauth-and-3rd-party-authentication

@alann-maulana - if you have a chance it would be fab if you could add the documentation here, it just involves adding the authdata and any useful explanation or links.

**Comment by alann-maulana** [comment]
@TomWFox  great, i would love to. I'll send PR for it soon.

**Comment by TomWFox** [comment]
PR merged.
