### ISSUE TITLE
🐛 Parse server api reference lot loading

### ISSUE THREAD

**Issue by nangyal** [ParsePlatform/Docs#721]
**Describe the bug**
Parse server api documentation reference not loading
constantly redirecting

**To Reproduce**
1. Go to https://parseplatform.org/parse-server/api/

**Screenshots**
![image](https://user-images.githubusercontent.com/15214137/76706032-72052700-66dc-11ea-889b-1d867894ec37.png)

**Desktop (please complete the following information):**
 - OS:win 10
 - Browser chrome 
 - Version 80

**Comment by TomWFox** [comment]
Thanks for reporting, I suspect I know the cause. I’ll try and take a look soon but feel free to submit a PR if you find a fix.

**Comment by TomWFox** [comment]
@nangyal Hi, looking into this now, do you have any idea when the issue may have started?

**Comment by TomWFox** [comment]
@acinader @dplewis I'm not sure what's causing this, I'm wondering whether its something relating to the travis deployment to GitHub pages on the parse-server repo, any ideas?

**Comment by acinader** [comment]
i re-ran the deploy phase and it fixed the problem.
