### ISSUE TITLE
📕Cloud code file triggers

### ISSUE THREAD

**Issue by TomWFox** [ParsePlatform/Docs#725]
__References:__
parse-community/parse-server#6344

__Proposed solution:__
https://docs.parseplatform.org/cloudcode/guide/

**Comment by stevestencil** [comment]
@TomWFox I can do this for sure... I will knock it out here shortly

**Comment by TomWFox** [comment]
Awesome, it looks like your addition of file metadata could be included too...
parse-community/Parse-SDK-JS/pull/1065
parse-community/Parse-SDK-JS/pull/1070
