### ISSUE TITLE
📙 fix guide typo

### ISSUE THREAD

**Issue by jhwsx** [ParsePlatform/Docs#745]
About guide, the part Objects -> Relational Data:

> By default, when fetching an object, related ParseObjects are not fetched. These objects’ values cannot be retrieved until they have been fetched like so:
```java
fetchedComment.getParseObject("post")
    .fetchIfNeededInBackground(new GetCallback<ParseObject>() {
        public void done(ParseObject post, ParseException e) {
          String title = post.getString("title");
          // Do something with your new title variable
        }
    });
```
`fetchedComment.getParseObject("post")` should be `fetchedComment.getParseObject("parent")`, right?

**Comment by TomWFox** [comment]
[Link to relevant section](http://docs.parseplatform.org/android/guide/#relational-data).

**Comment by TomWFox** [comment]
@jhwsx You're right...
```
// Add a relation between the Post and Comment
myComment.put("parent", myPost);
```
shows that the column name for the example is parent.

Would you like to make a PR?

**Comment by Jawnnypoo** [comment]
That would be great! I imagine the same error might exist in the iOS docs?

**Comment by TomWFox** [comment]
It does - [here](http://docs.parseplatform.org/ios/guide/#relational-data). I'm wondering whether the whole example should be switched to `post` instead of `parent` as `post` makes more sense contextually.

**Comment by Jawnnypoo** [comment]
Yep, I think `post` makes more sense.

**Comment by jhwsx** [comment]
A PR has been made.
