### ISSUE TITLE
📙 Google Sign In documentation needs update

### ISSUE THREAD

**Issue by kvnkuang** [ParsePlatform/Docs#754]
### Issue Description

Documentation for the Google Sign In function needs to be updated, reflecting changes introduced in version `4.13.0`:

1. `access_token` is no longer supported. Now, we have to use `id_token`.
2. `clientId` needs to be specified when initializing a `ParseServer` instance.
```
new ParseServer({
  ... // other settings
  google: {
    clientId: "your Google Sign In client ID"
  }
}
```

I am happy to submit a pull request.

Thanks,
Kevin

**Comment by kvnkuang** [comment]
Thanks @mtrezza, @SebC99 and @TomWFox. Did some research about the parameters and here's what I found.

> `clientId` is optional, it’s better to set it, but it should work without it.

That's correct. However, we should specify that to enable Google sign in, at least an empty `options` object is needed. Otherwise, this error will be triggered:

> Uncaught internal server error.Cannot destructure property 'clientId' of 'undefined' as it is undefined.

Something like this should be sufficient:

```
new ParseServer({
  ... // other settings
  google: { // make sure you pass at least an empty object
    clientId: "your Google Sign In client ID" // optional
  }
}
```

> As for `access_token` it’s correct as there’s not a single mention of an access_token in Google doc

`access_token` returned by Google's OAuth server can be used to perform an API request that requires user authorization. Doc is [here](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#obtainingaccesstokens).

It was supported in `parse-server` 4.2.0 and prior. Doc is [here](https://docs.parseplatform.org/parse-server/guide/#oauth-and-3rd-party-authentication).

Since it's no longer supported, we should change the example to:

```
{
  "google": {
    "id": "user's Google id (string)",
    "id_token": "an authorized Google id_token for the user",
  }
}
```

I can draft a pull request if everything makes sense.

**Comment by mtrezza** [comment]
> at least an empty options object is needed

Could we improve that in the auth adapter instead and simply use an empty object as default value (additional PR)?

> {
  "google": {
    "id": "user's Google id (string)",
    "id_token": "an authorized Google id_token for the user",
  }
}

If I understand correctly, old auth entries would still show the `access_token` field. Maybe it makes sense to document it as deprecated and where it comes from for historic reasons, to avoid confusion. "Deprecated" seems appropriate because `access_token` is still in use as all existing auth entries need to be still working.

**Comment by davimacedo** [comment]
closed by https://github.com/parse-community/parse-server/pull/6844
