### ISSUE TITLE
📙 Change mLab references to MongoDB

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/Docs#766]
__Link to section:__
https://docs.parseplatform.org/parse-server/guide/#deploying-to-glitch-and-mlab

__What is the issue?__
mLab has been bought by MongoDB, the mLab brand is discontinued; mLab does not allow to sign up for new accounts.

__Can you propose a solution?__
Change refs from mLab to MongoDB, as they also provide a free sandbox plan.

**Comment by TomWFox** [comment]
Duplicate of #704
