### ISSUE TITLE
Change the "Parse for IoT" apps term

### ISSUE THREAD

**Issue by TomWFox** [ParsePlatform/Docs#788]
Can we change the `"Parse for IoT" apps` term? I think this is rather confusing, I wouldn't know what this terms is referring to specifically. I think this simply means Parse that is used in an IoT environment?

_Originally posted by @mtrezza in https://github.com/parse-community/docs/pull/787#discussion_r522441122_

**Comment by TomWFox** [comment]
My suggestion is to simply change `"Parse for IoT" apps` to `IoT apps` at least where it makes grammatical sense.

**Comment by jaysonng** [comment]
If you guys are ok with changing "Parse for IoT" to "IoT apps", I can go ahead and make a pull request for this and check this open issue off.

**Comment by mtrezza** [comment]
Sure, please go ahead
