### ISSUE TITLE
📙 Fix Node Security link

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/Docs#796]
__Link to section:__
https://github.com/parse-community/parse-server/security/policy#communicating-with-us

__What is the issue?__
The `Node Security` link to https://nodesecurity.io/report redirects to https://www.npmjs.com. It is not clear for the user how to report a vulnerability.

__Can you propose a solution?__
Change link to: https://docs.npmjs.com/reporting-a-vulnerability-in-an-npm-package, but interestingly it says:
> On the package page, click Report a vulnerability.

But https://www.npmjs.com/package/parse-server does not have a "Report a vulnerability" button. Maybe this button also has to be enabled for the package.

**Comment by dblythy** [comment]
That would be good to have the button, I recently found the process of reporting a vulnerability to be difficult and ended up just sending an email through.

**Comment by TomWFox** [comment]
> But https://www.npmjs.com/package/parse-server does not have a "Report a vulnerability" button. Maybe this button also has to be enabled for the package.

I don't have access to check but I looked at a few other popular packages and none had such a button. Have you seen one?

**Comment by mtrezza** [comment]
Never seen one, only in a npm blog post screenshot from 2018:

https://blog.npmjs.org/post/179430064885/writing-quality-vulnerability-reports

**Comment by mtrezza** [comment]
Now I am starting to believe that they simply renamed the button to "Report a malware". It seems as if they consider a package with a security flaw to be a "malware", or maybe the part of the code that created the vulnerability to be "malware", in their terminology. Or maybe they don't process vulnerabilities anymore, only explicit malware that is included in a package?

The report form says:
> Please fill out the form to report malware in an npm package to the npm Security team.
> ...
> Please include any references, commits, or code examples that would be useful in reproducing the security issue.

Maybe we should simply link to this:
https://www.npmjs.com/advisories/report?package=parse-server

Or someone with npm access (@dplewis, @davimacedo) can reach out to npm to ask them for clarification.
(Btw, acinader still appears as collaborator on npm.)

**Comment by TomWFox** [comment]
I don't think is is the malware button...
> In cases where malware is confirmed, the package will be removed and replaced with a security placeholder.

I've never heard of such actions being taken for a security vulnerability.

**Comment by mtrezza** [comment]
Interesting quote that you found there. To me this looks all mixed up, I think we should reach out to npm.

**Comment by mtrezza** [comment]
According to [this post](https://npm.community/t/how-to-submit-security-vulnerability-in-my-package-for-npm-audit/1447), someone from the npm security team writes that the "Report a vulnerability" button used to lead to the same url the current "Report malware" button leads to.

It appears the button has just been renamed, but we should confirm this with npm.

I have just reached out to the npm security team for clarification.

**Comment by TomWFox** [comment]
Interesting, if it can be used for reporting vulnerabilities it would also be good to know what there process is when they receive a report.

**Comment by mtrezza** [comment]
I have received the following response form the npm security team:

> Unfortunately we no longer triage vulnerability reports on behalf of maintainers. Our best advice is to keep an up-to-date Security policy on the package's GitHub repository, as Parse Server does. Any security advisories that the Parse Server team creates on GitHub will be imported to the npm database and shown through npm audit.
>
> If we're missing any security advisories for Parse Server please let us know.

If I understand correctly, the process would be:
1. User reports vulnerability via email to Parse team.
2. Parse team creates vulnerability advisory entry as draft.
3. Parse team fixes security issue.
4. Parse team creates release with fix.
5. Parse team changes vulnerability status from draft to published.
6. npm imports published vulnerability to npm audit.

Is that correct?

**Comment by davimacedo** [comment]
I think that's the process. At the end there is also an option that we use to opt in in which GitHub broadcast the vulnerability to the other projects using Parse Server as a dependency.

**Comment by mtrezza** [comment]
That is an option to set when a vulnerability is published?

I also wonder if instead of the user sending an email we can offer a form that directly creates a security advisory?

**Comment by mtrezza** [comment]
I also just received confirmation from the npm security team, that the process described [above](https://github.com/parse-community/docs/issues/796#issuecomment-733221104) is correct:

> [The process] is correct. Once the Parse team changes the advisory status to published, the advisory will be used to feed Dependabot on GitHub and npm audit. Creating the advisory in GitHub also allows you to request a CVE ID for the vulnerability.

**Comment by davimacedo** [comment]
> That is an option to set when a vulnerability is published?

Yes. I think the option I mentioned is this CVE ID they referred but I am not sure. I will pay more attention when publishing the next one.

> I also wonder if instead of the user sending an email we can offer a form that directly creates a security advisory?

That would be good. There was nobody checking those e-mails for a long time but I am now doing it almost daily for about 3 months. An automatic integration would help for sure.

**Comment by mtrezza** [comment]
> An automatic integration would help for sure.

It seems that may come in the future, as this [tweet](https://twitter.com/laserlemon/status/1133000765235171328) suggests:

> Yes, thank you for this feedback. We agree that the ultimate goal is to allow non-admin reporters. Working on the team that built this, I can tell you that we err on the side of restricting access and taking baby steps from there.

The [GitHub API](https://docs.github.com/en/free-pro-team@latest/graphql/reference/mutations) also does not seem to offer an endpoint to create a security advisory, so there seems to be no easy way to automate that at this moment.

**Comment by mtrezza** [comment]
An alternative could be to offer a form like Typeform or Google Forms which would then send an email to us. The benefit being that the vulnerability report we receive is somewhat structured compared to a free-text email.

**Comment by davimacedo** [comment]
Yes. It makes sense.

**Comment by mtrezza** [comment]
@davimacedo You've dealt with many vulnerability reports here, if you have time maybe you could suggest which fields we should add in such a form that helps us to process reports quickly? Otherwise I would just take some inspiration from the bug report template & security advisory form.

I have also looked at hackerone.com which seem to provide a GitHub integration, but haven't found out much yet.

I'm also looking into a Discourse plugin to build a form, so we could host it as part of our forum.

**Comment by mtrezza** [comment]
I think using the [Discourse wizard plugin](https://meta.discourse.org/t/custom-wizard-plugin/73345) makes most sense, since it would be hosted as part of our Forum and we have full control over it.

@TomWFox What do you think about trying this out and installing the plugin in the forum? If a plugin is difficult to maintain, maybe we rather go with a hosted form like Google Forms.

**Comment by TomWFox** [comment]
I would like to use a Discourse plugin. The one you have suggested does seem well maintained (which does seem somewhat rare outside of the official Discourse ones).

It seems the key is [when to update](https://thepavilion.io/t/pavilions-support-policy-and-schedule/3312), we are on the `tests-passed` branch so we could update in the first 5 days of each month as they suggest. I'm not sure how one is supposed to ensure the specific commit to `tests-passed` is compatible with a commit in the first 5 days of the month, especially considering there are multiple commits per day to `tests-passed`.

We could just wing it, but if we want to be somewhat certain that the form will be stable it will require some more effort when updating.

**Comment by mtrezza** [comment]
I have no opinion regarding the reliability question, I am not familiar with how well Discourse / the plugin is maintained. If you think this does not provide a stable form (which I think we require, given the intended purpose), I'm ok with a free 3rd party service, but I'm also ok with giving the plug-in a try if you think it's ok.

**Comment by TomWFox** [comment]
Let's give the plugin a go, it won't be difficult to switch to a 3rd party service if we encounter problems. I'll install the plugin, is it ok if I make you admin to setup?

**Comment by mtrezza** [comment]
Sure, thanks.

**Comment by TomWFox** [comment]
Done, the setup can be done [here](https://community.parseplatform.org/admin/wizards/wizard).

**Comment by mtrezza** [comment]
It seems that the plug-in is not accessible for guests, only for logged in users.

When opening a wizard URL as a guest, one needs to go through the Forum sign-up process including email verification to create an account, just to land on the main page, instead of the wizard page. This process does not really seem to work well for submitting a vulnerability report.

This [issue](https://thepavilion.io/t/redirect-to-login-if-guest-visits-wizard/1831) confirms that a guest is required to sign-up to access the wizard, although they suggest that after sign-up the user should be redirected to the wizard, which was not the case in my tests (using Safari browser). They confirmed this being an issue, according to the [fix](https://github.com/paviliondev/discourse-custom-wizard/pull/17) the redirect could be browser dependent.

My conclusion would be that the plug-in does not seem suitable for reporting security vulnerabilities, because the wizard redirect does not seem to work reliably across browsers and together with the Forum sign-up requirement this process can be rather confusing.

**Comment by TomWFox** [comment]
That's a shame, I think it would be unreasonable to ask those wanting to report a vulnerability to make an account.

I guess 3rd party service it is, would you like to look at the price point and pros/cons of different options? I'm a fan of typeform but I imagine their free plan is somewhat more restrictive than that of Google Forms.

**Comment by mtrezza** [comment]
Yes, I'll look into these 3rd party forms.

I think the Wizard plug-in could still be an interesting feature for the forum, maybe you want to keep it installed. It allows a wizard after sign-up, e.g. to accept code of conduct. It could also be used for more complex user surveys, should we want to conduct that in the future.

**Comment by TomWFox** [comment]
Yes, it does seem quite powerful, I'll leave it installed.

**Comment by mtrezza** [comment]
I have implemented a 3rd party form (JotForm) to report a vulnerability for the [parse-server-api-mail-adapter](https://github.com/mtrezza/parse-server-api-mail-adapter/blob/main/SECURITY.md) which works fine.

- It even offers a mobile app that sends a push notification when a new vulnerability has been submitted.
- It is free (up to 5 forms) and it's one of the most versatile and configurable form builders I came across.
- It is free but promotes itself in footers (email and page) quite extensively.

We could use that for Parse Server.

**Comment by TomWFox** [comment]
That looks good to me. Is it possible to have an email when a new submission is made?

**Comment by mtrezza** [comment]
Sure, push notification, email and 3rd party integrations like Slack or just a generic webhook.
The free plan has 1k monthly form views and 100 monthly form submissions included, which should be enough if we use it just for vulnerability reporting.

**Comment by TomWFox** [comment]
Yes I think that should be fine. Do you think we should use the form for multiple repos or just for Parse Server?

**Comment by mtrezza** [comment]
All Parse repos I'd think. The mail adapter form already contains a drop down to select a repo as an example. I think we could auto-populate the drop down if Github provides an easy API.

**Comment by TomWFox** [comment]
Sounds good!

**Comment by mtrezza** [comment]
If I create a JotForm account, which email address should I use?

**Comment by TomWFox** [comment]
You could use community@parseplatform.org

**Comment by mtrezza** [comment]
I don't have access to that account, can someone please click on the verify email link?
Where do I post the login credentials for JotForm?

**Comment by TomWFox** [comment]
Done.

Hmmm, I really should get that 1Password account setup. As far as I'm concerned its fine if you keep them for now, we can share when necessary/when we've got a 1P!

**Comment by mtrezza** [comment]
I created a form https://form.jotform.com/210205133587044

- The repository list is not populated automatically, that is technically possible with their API, but I think not feasible given that we just try this out.
- I added a "provisional" data privacy clause with some key elements at the bottom which is legally mandatory if we store and process data of the majority of users by now. We could move that to the Vulnerability Disclosure Program page to simplify the form.
- Submissions will send an email to community[@]parseplatform.com as well as a push notification if you download their mobile app.
- The form could also be embedded with a <script> tag, if we want to dedicate a page on parseplatform.org.

Let me know any feedback to the form. @davimacedo maybe you can look over this since you are very engaged in vulnerability reports and see if any additional fields would help us.

**Comment by TomWFox** [comment]
Just thought - it would be useful to have the option to provide one’s GitHub username so then we can add them to a draft advisory for further info etc

**Comment by TomWFox** [comment]
It looks great! it could be nice to embed in on the website but the priority is to get people using it as this should be a marked improvement.

**Comment by mtrezza** [comment]
> provide one’s GitHub username so then we can add them to a draft advisory for further info etc

- If one provides the GH username, I think we don't have to require the email field; should we make this an "either-or" condition? Or should we not require any contact info at all,  and allow to submit the form without email or GH user?

**Comment by mtrezza** [comment]
I have removed the data privacy text and instead added a link to the T&C of the [Parse Community Vulnerability Disclosure Program](https://github.com/parse-community/parse-server/security/policy). This simplifies the form and we can add that text to a Parse Community Privacy Policy in general.

> The data entered here will be stored and used for the purpose of documenting and fixing this vulnerability. The data may be stored outside of your country and outside of your legislative region under circumstances that are less secure than the data privacy laws within your legislative region. For any questions regarding the content, correction or deletion of your data please contact community[@]parseplatform.com.

**Comment by mtrezza** [comment]
Since the community is using some popular 3rd party modules, and the 3rd party may not have a working vulnerability report process, I added this note to the repo dropdown:

> The repository for which you want to report a vulnerability. If the repository is not listed, it may be a 3rd party repository that is not managed by Parse Platform. In that case you can report the issue directly to the 3rd party, or report it using this form and we will do our best to triage and relay your report to the 3rd party.

**Comment by mtrezza** [comment]
We could also create a DNS record `report.parseplatform.org` that points to the form. To make sure that we (or others) don't reference the form URL directly, which can easily change in the future.

**Comment by mtrezza** [comment]
Should the form send the emails to security[@]parseplatform.org or community@... or do they land in the same inbox anyway?

**Comment by TomWFox** [comment]
> > provide one’s GitHub username so then we can add them to a draft advisory for further info etc
> 
> * If one provides the GH username, I think we don't have to require the email field; should we make this an "either-or" condition? Or should we not require any contact info at all,  and allow to submit the form without email or GH user?

I don’t think it’s a necessity to have contact info but should be encouraged. Perhaps we make both email and GH user optional for now and if it becomes and issue we can reassess.

**Comment by TomWFox** [comment]
DNS record is a good idea @davimacedo, could you set up a record to point `report.parseplatform.org` to `https://form.jotform.com/210205133587044`

It all ends up in the same inbox, the slight benefit of community@ right now is that the emails get forwarded to me (& Davi and Diamond I assume) so I don’t have to sign into the account to see them.

I don’t suppose there is an api endpoint to create draft advisories?

**Comment by mtrezza** [comment]
>  Perhaps we make both email and GH user optional 

Done.

> the slight benefit of community@ 

The form will send to community@ then.

> I don’t suppose there is an api endpoint to create draft advisories?

Unfortunately not, but I think in the near future we'll get a form on GitHub to report vulnerabilities, which will deprecate our form. There have been indications from the GH team that works on that feature group.

**Comment by mtrezza** [comment]
I'm rewriting the SECURITY.md; should we keep the email?

> All vulnerabilities should be privately reported to us by going to [report.parseplatform.org](https://report.parseplatform.org). Alternatively, you can send an email to [security&#64;parseplatform&#46;org](mailto:security&#64;parseplatform&#46;org).
>
> If you want you can encrypt your email to us by using our PGP public key, which is also uploaded [here](hkp://pgp.mit.edu):
> ...

**Comment by TomWFox** [comment]
I would leave is as a secondary option but remove the encryption key, I don't know if anyone even has the private key.

**Comment by mtrezza** [comment]
Done, https://github.com/parse-community/parse-server/pull/7081 is ready for review.
