### ISSUE TITLE
Restore full Security Guide

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Docs#86]
Some of the sections in the Security guide seem to have been lost in the transition to the new Docs version. Take a look at https://web.archive.org/web/20150422120021/https://parse.com/docs/data where some of the newer sections on CLP/ACL interactions can be seen, which are missing from parse.com/docs/ios/guide#security

**Comment by jkarraker** [comment]
I think there are other parts that did not make the transition also, for example he breakdown of the 6 CLP permission types into read and write.
