### ISSUE TITLE
📙 Refurbishment of Python code examples

### ISSUE THREAD

**Issue by cyb3rko** [ParsePlatform/Docs#894]
__Link to section:__
I don't know how many doc entries contain Python code but in the REST API guide are most of them:
https://docs.parseplatform.org/rest/guide

__What is the issue?__
The shown Python 2 code is outdated and gives instant errors if you try to run it in Python 3 (which is out since 2008, so definitely the today's standard):

![image](https://user-images.githubusercontent.com/46033730/183244622-b083b6b4-e3fd-45df-8878-b01cbe2dd0b0.png)

__Can you propose a solution?__
To just make it work again it would be

```python
import json,http.client   # new import
connection = http.client.HTTPSConnection('YOUR.PARSE-SERVER.HERE', 443)   # using new import
connection.connect()
connection.request('GET', '/parse/classes/GameScore', '', {
    "X-Parse-Application-Id": "${APPLICATION_ID}",
    "X-Parse-REST-API-Key": "${REST_API_KEY}"
})
result = json.loads(connection.getresponse().read())
print(result)   # changed print syntax
```

But according to the PEP 8 coding guidelines the [imports should be on seperate lines](https://peps.python.org/pep-0008/#imports) and there should be [2 blank lines after the import section](https://stackoverflow.com/questions/2953250/python-pep8-blank-lines-convention/47448739):

```python
import http.client
import json


...
```
---

Do we want to renew all the Python examples step by step to have modern examples you can directly use without errors and Googling what to change to make everything work again???

I'm interested in doing this if you say we want this to be done.

**Comment by mtrezza** [comment]
I'd say that would be preferred. Is there a reason why it wouldn't be?

**Comment by cyb3rko** [comment]
Alright. I don't think there's a reason not to do so.

**Comment by mtrezza** [comment]
Got it. In that case it would be fantastic if you wanted to take this on.
