### ISSUE TITLE
Endpoint `loginAs` is falsely documented to require GET request

### ISSUE THREAD

**Issue by aclec** [ParsePlatform/Docs#895]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
I'm trying to log by REST API with /loginAs and the answer is "Cannot GET /parse/loginAs".
But it's working with POST request. Is it just an error in the documentation ?

### Steps to reproduce
Make GET request on /loginAs like it's write on documentation.

### Environment

Server
- Parse Server version: `5.2.4`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

**Comment by mtrezza** [comment]
A log-in method always has to be a POST request, because it's not idempotent. If you look at the code, it's correctly implemented as a POST route:

https://github.com/parse-community/parse-server/blob/4c29d4d23b67e4abaf25803fe71cae47ce1b5957/src/Routers/UsersRouter.js#L481-L483

Where in the docs did you read that a GET request should be used?

**Comment by aclec** [comment]
@mtrezza on the Rest api doc:
https://docs.parseplatform.org/rest/guide/#user-impersonation

**Comment by mtrezza** [comment]
I transferred the issue to the docs repo. Would you mind opening a PR to correct the docs?

**Comment by aclec** [comment]
Sure, I'll do that

**Comment by mtrezza** [comment]
Closing via #897
