### ISSUE TITLE
Fix docs page

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/Docs#932]
### Issue

The docs page (https://docs.parseplatform.org) is an outdated version of the main page's section of docs (https://parseplatform.org). Both are maintained separately, which is difficult and causes one of them to be now outdated.

The outdated https://docs.parseplatform.org is visited more than the main page https://parseplatform.org, because for developers searching for docs online the https://docs.parseplatform.org  has a higher ranking in search results.

### Solution

De-duplicate both pages.

**Comment by mbfakourii** [comment]
The problem is that both pages are in separate repositories!

**Comment by mtrezza** [comment]
Right, any idea how to solve this? If not, I suggest we remove the docs links from the front page (to make it more compact) and move everything to the docs page.

**Comment by mbfakourii** [comment]
There are two suggestions
1=Transfer this repository to the doc repository or vice versa.
2=Remove the docs section from the main page's and the link to `docs.parseplatform.org`

My suggestion is the second option

**Comment by mtrezza** [comment]
I also think the 2nd option makes more sense.

**Comment by mbfakourii** [comment]
@dblythy

Did you have a special reason for closing? I wanted to work on this?!

**Comment by dblythy** [comment]
It has been completed by #933

**Comment by mtrezza** [comment]
We should add a PR template to this repo so PRs are liked to the issue.
