### ISSUE TITLE
Update Express Project Generation Instructions

### ISSUE THREAD

**Issue by whatasunnyday** [ParsePlatform/Docs#95]
https://www.parse.com/docs/js/guide#hosting-creating-a-web-app

> After you get Parse Hosting set up, you can generate a starter web app by typing the following inside your parse project folder.
>
> ```
> $ parse generate express
> ```

```
λ →  parse version   
2.0.12
λ →  parse generate express
unexpected arguments:[express]

Generates a sample app in the current project directory

Usage: 
  parse generate [flags]
Flags:
  -t, --type="express-ejs": Type of templates to use for generation.

Global Flags:
  -h, --help=false: help for generate
```

**Comment by pavanka** [comment]
you can now do the same thing as

parse generate

if you want to specify the type then use
parse generate --type="express-ejs"
or parse generate --type="express-jade"

we will correct the documentation with these details. thanks for reporting!

**Comment by hramos** [comment]
Thanks for flagging! We'll add this to our queue of documentation tasks. If you'd like to take a shot at updating this, feel free to open a pull request.

**Comment by whatasunnyday** [comment]
Thanks @pavanka & @hramos. I'm happy to send a PR but is there a documented list (or source code) of the web server and templates available?

**Comment by hramos** [comment]
Express is the only server that's supported right now.[ EJS and Jade](https://parse.com/docs/ios/guide#hosting-rendering-templates) are the only templating engines we support right now as well.
